namespace ProtoDesigner.CodeGen.CSharp;

/// <summary>
/// The bit reader and writer the generated C# codec runs on.
/// </summary>
/// <remarks>
/// <para>
/// Deliberately the same algorithm as <c>protodesigner_runtime.h</c>, bit for bit: the stream fills from
/// the top of each byte downwards, and the bit order decides which end of the <em>value</em> is consumed
/// first. The two targets speak one wire format, so any difference here would be a defect rather than a
/// design choice — which is why <c>CSharpWireCrossCheck</c> compares the output against the reference
/// codec rather than against the C generator.
/// </para>
/// <para>
/// It is emitted rather than shipped as a library for the same reason the C runtime is a header: generated
/// code that needs a NuGet package to build is generated code most people cannot use.
/// </para>
/// </remarks>
internal static class CSharpRuntime
{
    public const string FileName = "ProtoDesignerRuntime.cs";

    public static string Emit(string ns) => $$"""
    // -----------------------------------------------------------------------------
    //  Generated by ProtoDesigner. Do not edit.
    //
    //  The bit-level plumbing the generated codecs run on. Byte for byte identical
    //  to the C target's runtime: both write the same frames.
    // -----------------------------------------------------------------------------

    using System;

    namespace {{ns}}
    {
        /// <summary>Byte order of a field wider than eight bits.</summary>
        public enum PdEndian
        {
            Little = 0,
            Big = 1,
        }

        /// <summary>Which end of the value is written to the stream first.</summary>
        public enum PdBitOrder
        {
            MsbFirst = 0,
            LsbFirst = 1,
        }

        /// <summary>The outcome of a decode: where it stopped when it could not finish.</summary>
        public readonly struct PdDecodeResult
        {
            public PdDecodeResult(bool ok, int failedAtBit)
            {
                Ok = ok;
                FailedAtBit = failedAtBit;
            }

            public bool Ok { get; }

            /// <summary>Bit offset the decoder had reached when the frame ran out. Zero on success.</summary>
            public int FailedAtBit { get; }

            public static PdDecodeResult Success() => new PdDecodeResult(true, 0);

            public static PdDecodeResult Fail(int atBit) => new PdDecodeResult(false, atBit);
        }

        /// <summary>Writes values into a caller-owned buffer, a bit at a time.</summary>
        /// <remarks>
        /// Never allocates and never grows the buffer. Running past the end sets <see cref="Overflowed"/>
        /// and drops the write, so a caller that sized its buffer with <c>MaxBytes</c> cannot corrupt
        /// memory by getting a count wrong.
        /// </remarks>
        public struct PdBitWriter
        {
            private readonly byte[] _data;
            private readonly int _capacityBits;
            private int _cursor;
            private bool _overflow;

            public PdBitWriter(byte[] data)
            {
                _data = data ?? throw new ArgumentNullException(nameof(data));
                _capacityBits = data.Length * 8;
                _cursor = 0;
                _overflow = false;
                Array.Clear(_data, 0, _data.Length);
            }

            public int BitLength => _cursor;

            public int ByteLength => (_cursor + 7) / 8;

            public bool Overflowed => _overflow;

            public void Skip(int bits) => _cursor += bits;

            /// <summary>Advances to the next multiple of <paramref name="alignmentBits"/>.</summary>
            public void PadTo(int alignmentBits)
            {
                if (alignmentBits <= 0) return;
                int mod = _cursor % alignmentBits;
                if (mod != 0) _cursor += alignmentBits - mod;
            }

            public void WriteUnsigned(ulong value, int width, PdEndian endian, PdBitOrder order)
            {
                if (width <= 0 || width > 64) { _overflow = true; return; }
                if (_cursor + width > _capacityBits) { _overflow = true; return; }

                // Byte-aligned whole bytes, MSB-first: copy across. LSB-first reverses the bits inside
                // every byte, so the shortcut would be wrong rather than merely faster.
                if (order == PdBitOrder.MsbFirst && (_cursor % 8) == 0 && (width % 8) == 0)
                {
                    int bytes = width / 8;
                    int at = _cursor / 8;
                    if (endian == PdEndian.Big)
                    {
                        for (int i = 0; i < bytes; i++)
                            _data[at + i] = (byte)((value >> ((bytes - 1 - i) * 8)) & 0xFFu);
                    }
                    else
                    {
                        for (int i = 0; i < bytes; i++)
                            _data[at + i] = (byte)((value >> (i * 8)) & 0xFFu);
                    }
                    _cursor += width;
                    return;
                }

                for (int i = 0; i < width; i++)
                {
                    int source = order == PdBitOrder.LsbFirst ? i : (width - 1 - i);
                    if (((value >> source) & 1UL) != 0)
                    {
                        _data[_cursor / 8] |= (byte)(1u << (7 - (_cursor % 8)));
                    }
                    _cursor++;
                }
            }

            public void WriteSigned(long value, int width, PdEndian endian, PdBitOrder order)
            {
                ulong mask = width >= 64 ? ulong.MaxValue : ((1UL << width) - 1UL);
                WriteUnsigned(unchecked((ulong)value) & mask, width, endian, order);
            }

            public void WriteBytes(byte[] bytes, int count)
            {
                for (int i = 0; i < count; i++)
                    WriteUnsigned(bytes[i], 8, PdEndian.Little, PdBitOrder.MsbFirst);
            }
        }

        /// <summary>Reads values back out of a frame, a bit at a time.</summary>
        public struct PdBitReader
        {
            private readonly byte[] _data;
            private readonly int _sizeBits;
            private int _cursor;
            private bool _underflow;

            public PdBitReader(byte[] data, int sizeBytes)
            {
                _data = data ?? throw new ArgumentNullException(nameof(data));
                _sizeBits = sizeBytes * 8;
                _cursor = 0;
                _underflow = false;
            }

            public int BitOffset => _cursor;

            public bool Underflowed => _underflow;

            public bool AtEnd => _cursor >= _sizeBits;

            /// <summary>Bits left in the frame. Zero once the cursor has reached or passed the end.</summary>
            public int BitsRemaining => _cursor >= _sizeBits ? 0 : _sizeBits - _cursor;

            public void Skip(int bits) => _cursor += bits;

            public void AlignTo(int alignmentBits)
            {
                if (alignmentBits <= 0) return;
                int mod = _cursor % alignmentBits;
                if (mod != 0) _cursor += alignmentBits - mod;
            }

            /// <summary>
            /// True when the bytes at bit offset <paramref name="at"/> equal <paramref name="bytes"/>.
            /// Never moves the cursor, so a decoder can look ahead for a terminator before committing to
            /// reading another element.
            /// </summary>
            public bool MatchBytesAt(int at, byte[] bytes)
            {
                if ((at % 8) != 0) return false;
                if (at + (bytes.Length * 8) > _sizeBits) return false;
                for (int i = 0; i < bytes.Length; i++)
                {
                    if (_data[(at / 8) + i] != bytes[i]) return false;
                }
                return true;
            }

            public ulong ReadUnsigned(int width, PdEndian endian, PdBitOrder order)
            {
                if (width <= 0 || width > 64) { _underflow = true; return 0; }
                if (_cursor + width > _sizeBits) { _underflow = true; return 0; }

                if (order == PdBitOrder.MsbFirst && (_cursor % 8) == 0 && (width % 8) == 0)
                {
                    int bytes = width / 8;
                    int at = _cursor / 8;
                    ulong result = 0;
                    if (endian == PdEndian.Big)
                    {
                        for (int i = 0; i < bytes; i++) result = (result << 8) | _data[at + i];
                    }
                    else
                    {
                        for (int i = bytes - 1; i >= 0; i--) result = (result << 8) | _data[at + i];
                    }
                    _cursor += width;
                    return result;
                }

                ulong value = 0;
                for (int i = 0; i < width; i++)
                {
                    ulong bit = (ulong)((_data[_cursor / 8] >> (7 - (_cursor % 8))) & 1);
                    if (order == PdBitOrder.LsbFirst) value |= bit << i;
                    else value = (value << 1) | bit;
                    _cursor++;
                }
                return value;
            }

            public long ReadSigned(int width, PdEndian endian, PdBitOrder order)
            {
                ulong raw = ReadUnsigned(width, endian, order);
                if (width >= 64) return unchecked((long)raw);

                ulong signBit = 1UL << (width - 1);
                if ((raw & signBit) == 0) return unchecked((long)raw);
                return unchecked((long)(raw | ~((1UL << width) - 1UL)));
            }
        }

        /// <summary>Round-to-nearest, matching the C target's <c>pd_quantize</c>.</summary>
        /// <remarks>
        /// A cast truncates toward zero, so a scaled field would never reach the top code its width was
        /// chosen for and every reading would be biased low by up to a whole code.
        /// </remarks>
        public static class PdMath
        {
            public static long Quantize(double v) => (long)(v < 0.0 ? v - 0.5 : v + 0.5);
        }

        /// <summary>Builds an array whose elements are already constructed.</summary>
        /// <remarks>
        /// <c>new Block[4]</c> is four nulls, so a decoder writing into <c>blocks[i].Field</c> would throw
        /// before it read a byte. The array's length is the protocol's capacity and every slot has to be
        /// usable; how many are live is the count's job.
        /// </remarks>
        public static class PdInit
        {
            public static T[] Array<T>(int length) where T : new()
            {
                var items = new T[length];
                for (int i = 0; i < length; i++) items[i] = new T();
                return items;
            }
        }

        /// <summary>IEEE-754 bit patterns, so a float goes on the wire verbatim rather than through a cast.</summary>
        public static class PdFloat
        {
            public static uint ToBits(float v) => BitConverter.ToUInt32(BitConverter.GetBytes(v), 0);

            public static float FromBits(uint bits) => BitConverter.ToSingle(BitConverter.GetBytes(bits), 0);

            public static ulong ToBits(double v) => BitConverter.ToUInt64(BitConverter.GetBytes(v), 0);

            public static double FromBits(ulong bits) => BitConverter.ToDouble(BitConverter.GetBytes(bits), 0);
        }
    }

    """;
}
