using System.Diagnostics;
using System.Globalization;
using System.Text;
using ProtoDesigner.CodeGen.C;
using ProtoDesigner.CodeGen.Runtime;

namespace ProtoDesigner.CodeGen.Tests;

/// <summary>
/// Compiles the generated C and checks it against the C# reference codec, value by value, over the
/// whole wire matrix.
/// </summary>
/// <remarks>
/// The two implementations are independent, so anywhere they disagree one of them is wrong — that is the
/// entire point. Round-tripping the generated code against itself would happily agree with a bug in both
/// directions; only the cross-check pins the actual wire format down.
///
/// The driver is compiled twice from the same source — once as C, once as C++ — because "one header
/// serves both languages" is a claim the output makes and therefore a claim worth testing. Compiling
/// only as C++ would let a C-invalid header through unnoticed, which is the whole reason this target
/// stopped being a C++ generator.
///
/// The compiler is located automatically. On a machine without MSVC the generation and driver-emission
/// are still exercised and the compile step is reported as skipped rather than failing the build.
/// </remarks>
public class CCrossCheck
{
    private static readonly ReferenceCodec Codec = new();

    internal const string Prefix = "proto";

    [Fact]
    public void The_generated_c_agrees_with_the_reference_codec_across_the_whole_matrix()
    {
        var cases = WireMatrix.Cases();
        var (project, bus) = WireMatrix.Build(cases);
        var ir = new IrBuilder().Build(project, bus);

        var set = new CGenerator().Generate(ir, new GeneratorOptions(Namespace: Prefix));

        var dir = Path.Combine(Path.GetTempPath(), $"pd-crosscheck-{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        try
        {
            foreach (var file in set.Files)
            {
                if (!file.RelativePath.EndsWith(".h", StringComparison.Ordinal)) continue;
                File.WriteAllText(Path.Combine(dir, file.RelativePath), file.Contents);
            }

            // The bus header: not the runtime, not the shared type declarations (which it includes).
            var headerName = set.Files.Single(f =>
                f.RelativePath.EndsWith(".h", StringComparison.Ordinal) &&
                f.RelativePath != RuntimeHeaderName &&
                !f.RelativePath.EndsWith("_types.h", StringComparison.Ordinal)).RelativePath;

            var (driver, checkCount) = EmitDriver(ir, cases, headerName);
            File.WriteAllText(Path.Combine(dir, "crosscheck.c"), driver);

            Assert.True(checkCount > 1000, $"Only {checkCount} checks emitted — the matrix has shrunk.");

            var compiler = MsvcLocator.Find();
            Assert.True(compiler is not null || MsvcLocator.SkipRequested,
                "No MSVC toolchain found, so the generated C was never compiled — the half of this test "
                + "that actually proves anything did not run. Install the VC++ build tools, or set "
                + $"{MsvcLocator.SkipVariable}=1 to accept generation-only coverage.");

            if (compiler is null) return;   // explicitly opted out above

            foreach (var language in new[] { MsvcLanguage.C, MsvcLanguage.Cpp })
            {
                var (exitCode, output) = MsvcLocator.CompileAndRun(compiler, dir, "crosscheck.c", language);
                Assert.True(exitCode == 0,
                    $"Compiled as {language}, the generated code disagreed with the reference codec "
                    + $"({checkCount} checks):\n{output}");
            }
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { /* best effort */ }
        }
    }

    private const string RuntimeHeaderName = "protodesigner_runtime.h";

    /// <summary>
    /// Emits a self-checking program: for every case and value it encodes, compares the bytes against
    /// what the C# codec produced, decodes again, and compares the value back.
    /// </summary>
    /// <remarks>
    /// The source is deliberately written in the subset that is valid C <em>and</em> valid C++ — plain
    /// <c>printf</c>, C-style casts, <c>= {0}</c> initialisers — because the same file is compiled both
    /// ways. Anything C++-only here would quietly turn the C compile into a test of nothing.
    /// </remarks>
    private static (string Source, int Checks) EmitDriver(
        ProtocolIr ir, IReadOnlyList<WireMatrix.Case> cases, string headerName)
    {
        var sb = new StringBuilder();
        var checks = 0;

        sb.AppendLine("/* Generated by CCrossCheck. Compares the generated C against the C# reference codec. */");
        sb.AppendLine($"#include \"{headerName}\"");
        sb.AppendLine("#include <stdio.h>");
        sb.AppendLine("#include <string.h>");
        sb.AppendLine();
        sb.AppendLine("static int failures = 0;");
        sb.AppendLine();
        sb.AppendLine("static void expect_bytes(const char* where, const uint8_t* got, size_t got_len,");
        sb.AppendLine("                         const uint8_t* want, size_t want_len) {");
        sb.AppendLine("    size_t i;");
        sb.AppendLine("    if (got_len != want_len || memcmp(got, want, want_len) != 0) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        printf(\"BYTES %s: got [\", where);");
        sb.AppendLine("        for (i = 0; i < got_len; ++i) printf(\"%02X \", got[i]);");
        sb.AppendLine("        printf(\"] want [\");");
        sb.AppendLine("        for (i = 0; i < want_len; ++i) printf(\"%02X \", want[i]);");
        sb.AppendLine("        printf(\"]\\n\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("static void expect_i64(const char* where, int64_t got, int64_t want) {");
        sb.AppendLine("    if (got != want) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        printf(\"VALUE %s: got %lld want %lld\\n\",");
        sb.AppendLine("               where, (long long)got, (long long)want);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var c in cases)
        {
            var msg = ir.Messages.Single(m => m.Name == c.Name);
            var structName = CNaming.TypeName(Prefix, c.Name);
            var maxBytes = CNaming.MacroName(Prefix, c.Name, "MAX_BYTES");
            var toWire = CNaming.FunctionName(Prefix, c.Name, "ConvertToWire");
            var toHost = CNaming.FunctionName(Prefix, c.Name, "ConvertToHost");

            sb.AppendLine($"static void check_{structName}(void) {{");

            foreach (var value in c.Values)
            {
                var values = WireMatrix.ValuesFor(c, value);
                var expected = Codec.Encode(msg, values);
                var literal = string.Join(", ", expected.Select(b => $"0x{b:X2}"));
                var where = $"{c.Name}@{WireMatrix.Format(value)}";

                sb.AppendLine("    {");
                sb.AppendLine($"        {structName} m;");
                sb.AppendLine($"        {structName} back;");
                sb.AppendLine($"        uint8_t wire[{maxBytes}];");
                sb.AppendLine($"        static const uint8_t want[] = {{ {literal} }};");
                sb.AppendLine("        size_t n;");
                sb.AppendLine("        memset(&m, 0, sizeof(m));");
                sb.AppendLine("        memset(&back, 0, sizeof(back));");
                for (var i = 0; i < c.LeadInBits; i++)
                    sb.AppendLine($"        m.lead{i} = {(i % 2 == 0 ? 1 : 0)};");
                sb.AppendLine($"        m.value = {ValueLiteral(c, value)};");
                sb.AppendLine($"        n = {toWire}(&m, wire, sizeof(wire));");
                sb.AppendLine($"        expect_bytes(\"{where}\", wire, n, want, sizeof(want));");
                sb.AppendLine($"        {toHost}(wire, n, &back);");
                sb.AppendLine($"        expect_i64(\"{where}\", (int64_t)(back.value), {ValueLiteral(c, value)});");
                sb.AppendLine("    }");

                checks += 2;
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("int main(void) {");
        foreach (var c in cases)
            sb.AppendLine($"    check_{CNaming.TypeName(Prefix, c.Name)}();");
        sb.AppendLine($"    printf(\"%d failure(s) over {checks} checks\\n\", failures);");
        sb.AppendLine("    return failures == 0 ? 0 : 1;");
        sb.AppendLine("}");

        return (sb.ToString(), checks);
    }

    /// <summary>
    /// A literal for the value, valid in C and C++ alike. The suffixes matter: an unsuffixed
    /// 0x8000000000000000 has no signed type to live in, and long.MinValue cannot be written as a
    /// negative literal without the compiler first forming its positive counterpart.
    /// </summary>
    private static string ValueLiteral(WireMatrix.Case c, long value)
    {
        if (c.Kind == PrimitiveKind.Bool) return value != 0 ? "true" : "false";

        if (!c.IsSigned)
        {
            var unsignedValue = c.Bits >= 64 ? unchecked((ulong)value) : (ulong)value;
            return unsignedValue.ToString(CultureInfo.InvariantCulture) + "ull";
        }

        if (value == long.MinValue) return "(-9223372036854775807ll - 1)";
        return value.ToString(CultureInfo.InvariantCulture) + "ll";
    }
}

/// <summary>Which language MSVC should treat the source as.</summary>
internal enum MsvcLanguage
{
    /// <summary>Force C (/TC), whatever the file extension says.</summary>
    C,

    /// <summary>Force C++ (/TP). The generated header claims to work here too; this is the proof.</summary>
    Cpp,
}

/// <summary>Finds an MSVC toolchain and builds a single-file program with it.</summary>
internal static class MsvcLocator
{
    /// <summary>
    /// Set to 1 to accept generation-only coverage on a machine with no C++ compiler.
    /// </summary>
    /// <remarks>
    /// Opting out has to be deliberate. The cross-check silently passing when it never compiled anything
    /// is the worst outcome available: a green suite that proves only that the generator produced text.
    /// </remarks>
    public const string SkipVariable = "PROTODESIGNER_SKIP_CPP_CROSSCHECK";

    public static bool SkipRequested =>
        Environment.GetEnvironmentVariable(SkipVariable) is "1" or "true";

    /// <summary>Path to vcvars64.bat, or null when no Visual Studio with the C++ tools is installed.</summary>
    public static string? Find()
    {
        if (!OperatingSystem.IsWindows()) return null;

        var programFiles = Environment.GetEnvironmentVariable("ProgramFiles(x86)")
                           ?? Environment.GetEnvironmentVariable("ProgramFiles");
        if (programFiles is null) return null;

        var vswhere = Path.Combine(programFiles, "Microsoft Visual Studio", "Installer", "vswhere.exe");
        if (!File.Exists(vswhere)) return null;

        var psi = new ProcessStartInfo(vswhere)
        {
            RedirectStandardOutput = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        foreach (var arg in new[]
                 {
                     "-latest", "-products", "*",
                     "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                     "-property", "installationPath",
                 })
            psi.ArgumentList.Add(arg);

        using var proc = Process.Start(psi);
        if (proc is null) return null;
        var installPath = proc.StandardOutput.ReadToEnd().Trim();
        proc.WaitForExit();

        if (string.IsNullOrEmpty(installPath)) return null;

        var vcvars = Path.Combine(installPath, "VC", "Auxiliary", "Build", "vcvars64.bat");
        return File.Exists(vcvars) ? vcvars : null;
    }

    /// <summary>Compiles at /W4 and runs the result, returning its exit code and output.</summary>
    /// <remarks>
    /// <para>
    /// The language is forced with /TC or /TP rather than left to the file extension, so the same source
    /// can be built both ways without copying it to a second name.
    /// </para>
    /// <para>
    /// The steps go into a .bat rather than onto cmd's command line. Passing a compound command through
    /// <see cref="ProcessStartInfo.ArgumentList"/> re-quotes it, and cmd then rejects the result silently
    /// with an empty stdout — which looks exactly like a compiler that found nothing wrong.
    /// </para>
    /// </remarks>
    public static (int ExitCode, string Output) CompileAndRun(
        string vcvars, string workingDir, string sourceFile, MsvcLanguage language = MsvcLanguage.C)
    {
        // /TC and /TP force the language; /std applies only to the C++ build, since MSVC rejects a C++
        // standard switch on a C translation unit.
        var languageFlags = language == MsvcLanguage.Cpp ? "/TP /std:c++14 /EHsc" : "/TC";
        var exe = language == MsvcLanguage.Cpp ? "crosscheck_cpp.exe" : "crosscheck_c.exe";

        // /bigobj: the matrix driver is one very large translation unit and overflows the default
        // section limit without it.
        var batch = Path.Combine(workingDir, "build.bat");
        File.WriteAllText(batch, string.Join("\r\n",
            "@echo off",
            $"call \"{vcvars}\" >nul 2>&1",
            $"cd /d \"{workingDir}\"",
            $"cl /nologo /W4 {languageFlags} /bigobj {sourceFile} /Fe:{exe}",
            "if errorlevel 1 exit /b 2",
            // Explicitly relative: NoDefaultCurrentDirectoryInExePath is set in some environments, and a
            // bare name then fails to resolve even though the file is right there.
            $".\\{exe}",
            "exit /b %errorlevel%") + "\r\n");

        var psi = new ProcessStartInfo("cmd.exe")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            WorkingDirectory = workingDir,
        };
        psi.ArgumentList.Add("/c");
        psi.ArgumentList.Add(batch);

        using var proc = Process.Start(psi)!;
        // Read both streams concurrently: a compiler that fills the stderr pipe while we block on stdout
        // would deadlock until the timeout.
        var stdoutTask = proc.StandardOutput.ReadToEndAsync();
        var stderrTask = proc.StandardError.ReadToEndAsync();
        proc.WaitForExit(milliseconds: 600_000);

        return (proc.ExitCode, Trim(stdoutTask.Result + stderrTask.Result));
    }

    /// <summary>
    /// Keeps the failure message readable when hundreds of cases disagree at once. Groups by host kind
    /// first, because a systematic fault shows up as a whole kind failing and that is the thing worth
    /// seeing before any individual byte comparison.
    /// </summary>
    private static string Trim(string text)
    {
        var lines = text.Split('\n');
        if (lines.Length <= 80) return text;

        // "BYTES U8_4b_Little_at0@15: …" → "U8"
        var byKind = lines
            .Select(l => l.Split(' ').Skip(1).FirstOrDefault() ?? "")
            .Where(t => t.Contains('_'))
            .GroupBy(t => t.Split('_')[0])
            .OrderByDescending(g => g.Count())
            .Select(g => $"  {g.Key}: {g.Count()} disagreement(s)")
            .ToList();

        var summary = byKind.Count > 0
            ? "Disagreements by host kind:\n" + string.Join('\n', byKind) + "\n\n"
            : "";

        // A few examples per kind beats sixty from whichever kind sorts first.
        var samples = lines
            .Where(l => l.Contains('_') && l.Contains('@'))
            .GroupBy(l => (l.Split(' ').Skip(1).FirstOrDefault() ?? "").Split('_')[0])
            .SelectMany(g => g.Take(6))
            .ToList();

        return summary + "Examples:\n" + string.Join('\n', samples) +
               $"\n\n({lines.Length} line(s) of output in total)";
    }
}
