using System.Diagnostics;
using System.Globalization;
using System.Text;
using ProtoDesigner.CodeGen.Cpp;
using ProtoDesigner.CodeGen.Runtime;

namespace ProtoDesigner.CodeGen.Tests;

/// <summary>
/// Compiles the generated C++ and checks it against the C# reference codec, value by value, over the
/// whole wire matrix.
/// </summary>
/// <remarks>
/// The two implementations are independent, so anywhere they disagree one of them is wrong — that is the
/// entire point. Round-tripping C++ against itself would happily agree with a bug in both directions;
/// only the cross-check pins the actual wire format down.
///
/// The compiler is located automatically. On a machine without MSVC the generation and driver-emission
/// are still exercised and the compile step is reported as skipped rather than failing the build.
/// </remarks>
public class CppCrossCheck
{
    private static readonly ReferenceCodec Codec = new();

    [Fact]
    public void The_generated_cpp_agrees_with_the_reference_codec_across_the_whole_matrix()
    {
        var cases = WireMatrix.Cases();
        var (project, bus) = WireMatrix.Build(cases);
        var ir = new IrBuilder().Build(project, bus);

        var set = new CppGenerator().Generate(ir, new GeneratorOptions(Namespace: "proto"));

        var dir = Path.Combine(Path.GetTempPath(), $"pd-crosscheck-{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        try
        {
            foreach (var file in set.Files)
            {
                if (!file.RelativePath.EndsWith(".h", StringComparison.Ordinal)) continue;
                File.WriteAllText(Path.Combine(dir, file.RelativePath), file.Contents);
            }

            // The bus header: not the runtime, not the shared type declarations (which it includes).
            var headerName = set.Files.Single(f =>
                f.RelativePath.EndsWith(".h", StringComparison.Ordinal) &&
                f.RelativePath != CppRuntimeHeaderName &&
                !f.RelativePath.EndsWith("_types.h", StringComparison.Ordinal)).RelativePath;

            var (driver, checkCount) = EmitDriver(ir, cases, headerName);
            File.WriteAllText(Path.Combine(dir, "crosscheck.cpp"), driver);

            Assert.True(checkCount > 1000, $"Only {checkCount} checks emitted — the matrix has shrunk.");

            var compiler = MsvcLocator.Find();
            Assert.True(compiler is not null || MsvcLocator.SkipRequested,
                "No MSVC toolchain found, so the generated C++ was never compiled — the half of this test "
                + "that actually proves anything did not run. Install the VC++ build tools, or set "
                + $"{MsvcLocator.SkipVariable}=1 to accept generation-only coverage.");

            if (compiler is null) return;   // explicitly opted out above

            var (exitCode, output) = MsvcLocator.CompileAndRun(compiler, dir, "crosscheck.cpp");
            Assert.True(exitCode == 0,
                $"The generated C++ disagreed with the reference codec ({checkCount} checks):\n{output}");
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { /* best effort */ }
        }
    }

    private const string CppRuntimeHeaderName = "protodesigner_runtime.h";

    /// <summary>
    /// Emits a self-checking C++ program: for every case and value it encodes, compares the bytes against
    /// what the C# codec produced, decodes again, and compares the value back.
    /// </summary>
    private static (string Source, int Checks) EmitDriver(
        ProtocolIr ir, IReadOnlyList<WireMatrix.Case> cases, string headerName)
    {
        var sb = new StringBuilder();
        var checks = 0;

        sb.AppendLine("// Generated by CppCrossCheck. Compares the generated C++ against the C# reference codec.");
        sb.AppendLine($"#include \"{headerName}\"");
        sb.AppendLine("#include <cstdio>");
        sb.AppendLine("#include <cstring>");
        sb.AppendLine();
        sb.AppendLine("static int failures = 0;");
        sb.AppendLine();
        sb.AppendLine("static void expect_bytes(const char* where, const uint8_t* got, size_t got_len,");
        sb.AppendLine("                         const uint8_t* want, size_t want_len) {");
        sb.AppendLine("    if (got_len != want_len || memcmp(got, want, want_len) != 0) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        std::printf(\"BYTES %s: got [\", where);");
        sb.AppendLine("        for (size_t i = 0; i < got_len; ++i) std::printf(\"%02X \", got[i]);");
        sb.AppendLine("        std::printf(\"] want [\");");
        sb.AppendLine("        for (size_t i = 0; i < want_len; ++i) std::printf(\"%02X \", want[i]);");
        sb.AppendLine("        std::printf(\"]\\n\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("static void expect_i64(const char* where, int64_t got, int64_t want) {");
        sb.AppendLine("    if (got != want) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        std::printf(\"VALUE %s: got %lld want %lld\\n\",");
        sb.AppendLine("                    where, (long long)got, (long long)want);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var c in cases)
        {
            var msg = ir.Messages.Single(m => m.Name == c.Name);
            var structName = CppNaming.TypeName(c.Name);
            var fn = $"check_{structName}";

            sb.AppendLine($"static void {fn}() {{");

            foreach (var value in c.Values)
            {
                var values = WireMatrix.ValuesFor(c, value);
                var expected = Codec.Encode(msg, values);
                var literal = string.Join(", ", expected.Select(b => $"0x{b:X2}"));
                var where = $"{c.Name}@{WireMatrix.Format(value)}";

                sb.AppendLine("    {");
                sb.AppendLine($"        proto::{structName} m{{}};");
                for (var i = 0; i < c.LeadInBits; i++)
                    sb.AppendLine($"        m.lead{i} = {(i % 2 == 0 ? 1 : 0)};");
                sb.AppendLine($"        m.value = {ValueLiteral(c, value)};");
                sb.AppendLine($"        uint8_t wire[proto::{structName}::kMaxBytes];");
                sb.AppendLine($"        size_t n = proto::{structName}_ConvertToWire(m, wire);");
                sb.AppendLine($"        static const uint8_t want[] = {{ {literal} }};");
                sb.AppendLine($"        expect_bytes(\"{where}\", wire, n, want, sizeof(want));");
                sb.AppendLine();
                sb.AppendLine($"        proto::{structName} back{{}};");
                sb.AppendLine($"        proto::{structName}_ConvertToHost(wire, n, back);");
                sb.AppendLine($"        expect_i64(\"{where}\", static_cast<int64_t>(back.value), {ValueLiteral(c, value)});");
                sb.AppendLine("    }");

                checks += 2;
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("int main() {");
        foreach (var c in cases)
            sb.AppendLine($"    check_{CppNaming.TypeName(c.Name)}();");
        sb.AppendLine($"    std::printf(\"%d failure(s) over {checks} checks\\n\", failures);");
        sb.AppendLine("    return failures == 0 ? 0 : 1;");
        sb.AppendLine("}");

        return (sb.ToString(), checks);
    }

    /// <summary>
    /// A C++ literal for the value. The suffixes matter: an unsuffixed 0x8000000000000000 has no signed
    /// type to live in, and long.MinValue cannot be written as a negative literal without the compiler
    /// first forming its positive counterpart.
    /// </summary>
    private static string ValueLiteral(WireMatrix.Case c, long value)
    {
        if (c.Kind == PrimitiveKind.Bool) return value != 0 ? "true" : "false";

        if (!c.IsSigned)
        {
            var unsignedValue = c.Bits >= 64 ? unchecked((ulong)value) : (ulong)value;
            return unsignedValue.ToString(CultureInfo.InvariantCulture) + "ull";
        }

        if (value == long.MinValue) return "(-9223372036854775807ll - 1)";
        return value.ToString(CultureInfo.InvariantCulture) + "ll";
    }
}

/// <summary>Finds an MSVC toolchain and builds a single-file program with it.</summary>
internal static class MsvcLocator
{
    /// <summary>
    /// Set to 1 to accept generation-only coverage on a machine with no C++ compiler.
    /// </summary>
    /// <remarks>
    /// Opting out has to be deliberate. The cross-check silently passing when it never compiled anything
    /// is the worst outcome available: a green suite that proves only that the generator produced text.
    /// </remarks>
    public const string SkipVariable = "PROTODESIGNER_SKIP_CPP_CROSSCHECK";

    public static bool SkipRequested =>
        Environment.GetEnvironmentVariable(SkipVariable) is "1" or "true";

    /// <summary>Path to vcvars64.bat, or null when no Visual Studio with the C++ tools is installed.</summary>
    public static string? Find()
    {
        if (!OperatingSystem.IsWindows()) return null;

        var programFiles = Environment.GetEnvironmentVariable("ProgramFiles(x86)")
                           ?? Environment.GetEnvironmentVariable("ProgramFiles");
        if (programFiles is null) return null;

        var vswhere = Path.Combine(programFiles, "Microsoft Visual Studio", "Installer", "vswhere.exe");
        if (!File.Exists(vswhere)) return null;

        var psi = new ProcessStartInfo(vswhere)
        {
            RedirectStandardOutput = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        foreach (var arg in new[]
                 {
                     "-latest", "-products", "*",
                     "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                     "-property", "installationPath",
                 })
            psi.ArgumentList.Add(arg);

        using var proc = Process.Start(psi);
        if (proc is null) return null;
        var installPath = proc.StandardOutput.ReadToEnd().Trim();
        proc.WaitForExit();

        if (string.IsNullOrEmpty(installPath)) return null;

        var vcvars = Path.Combine(installPath, "VC", "Auxiliary", "Build", "vcvars64.bat");
        return File.Exists(vcvars) ? vcvars : null;
    }

    /// <summary>Compiles at /W4 under C++14 and runs the result, returning its exit code and output.</summary>
    /// <remarks>
    /// The steps go into a .bat rather than onto cmd's command line. Passing a compound command through
    /// <see cref="ProcessStartInfo.ArgumentList"/> re-quotes it, and cmd then rejects the result silently
    /// with an empty stdout — which looks exactly like a compiler that found nothing wrong.
    /// </remarks>
    public static (int ExitCode, string Output) CompileAndRun(string vcvars, string workingDir, string sourceFile)
    {
        // /bigobj: the matrix driver is one very large translation unit and overflows the default
        // section limit without it.
        var batch = Path.Combine(workingDir, "build.bat");
        File.WriteAllText(batch, string.Join("\r\n",
            "@echo off",
            $"call \"{vcvars}\" >nul 2>&1",
            $"cd /d \"{workingDir}\"",
            $"cl /nologo /W4 /std:c++14 /EHsc /bigobj {sourceFile} /Fe:crosscheck.exe",
            "if errorlevel 1 exit /b 2",
            // Explicitly relative: NoDefaultCurrentDirectoryInExePath is set in some environments, and a
            // bare name then fails to resolve even though the file is right there.
            ".\\crosscheck.exe",
            "exit /b %errorlevel%") + "\r\n");

        var psi = new ProcessStartInfo("cmd.exe")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            WorkingDirectory = workingDir,
        };
        psi.ArgumentList.Add("/c");
        psi.ArgumentList.Add(batch);

        using var proc = Process.Start(psi)!;
        // Read both streams concurrently: a compiler that fills the stderr pipe while we block on stdout
        // would deadlock until the timeout.
        var stdoutTask = proc.StandardOutput.ReadToEndAsync();
        var stderrTask = proc.StandardError.ReadToEndAsync();
        proc.WaitForExit(milliseconds: 600_000);

        return (proc.ExitCode, Trim(stdoutTask.Result + stderrTask.Result));
    }

    /// <summary>
    /// Keeps the failure message readable when hundreds of cases disagree at once. Groups by host kind
    /// first, because a systematic fault shows up as a whole kind failing and that is the thing worth
    /// seeing before any individual byte comparison.
    /// </summary>
    private static string Trim(string text)
    {
        var lines = text.Split('\n');
        if (lines.Length <= 80) return text;

        // "BYTES U8_4b_Little_at0@15: …" → "U8"
        var byKind = lines
            .Select(l => l.Split(' ').Skip(1).FirstOrDefault() ?? "")
            .Where(t => t.Contains('_'))
            .GroupBy(t => t.Split('_')[0])
            .OrderByDescending(g => g.Count())
            .Select(g => $"  {g.Key}: {g.Count()} disagreement(s)")
            .ToList();

        var summary = byKind.Count > 0
            ? "Disagreements by host kind:\n" + string.Join('\n', byKind) + "\n\n"
            : "";

        // A few examples per kind beats sixty from whichever kind sorts first.
        var samples = lines
            .Where(l => l.Contains('_') && l.Contains('@'))
            .GroupBy(l => (l.Split(' ').Skip(1).FirstOrDefault() ?? "").Split('_')[0])
            .SelectMany(g => g.Take(6))
            .ToList();

        return summary + "Examples:\n" + string.Join('\n', samples) +
               $"\n\n({lines.Length} line(s) of output in total)";
    }
}
