using System.Globalization;
using System.Text;
using ProtoDesigner.CodeGen.Cpp;
using ProtoDesigner.CodeGen.Runtime;

namespace ProtoDesigner.CodeGen.Tests;

/// <summary>
/// The composite half of the C++ cross-check: enums, arrays, quantized floats and raw IEEE-754 floats,
/// compiled and compared against the C# reference codec.
/// </summary>
/// <remarks>
/// These are the shapes where the generator does real work rather than passing a value straight through —
/// an enum's cast via its underlying type, an array's per-element stride, a transform's divide-then-round.
/// A disagreement here means one of the two implementations has the wire format wrong.
/// </remarks>
public class CppCompositeCrossCheck
{
    private static readonly ReferenceCodec Codec = new();

    [Fact]
    public void Enums_arrays_and_floats_agree_between_the_generated_cpp_and_the_reference_codec()
    {
        var cases = CompositeMatrix.Cases();
        var (project, bus) = CompositeMatrix.Build(cases);
        var ir = new IrBuilder().Build(project, bus);

        var set = new CppGenerator().Generate(ir, new GeneratorOptions(Namespace: "proto"));

        var dir = Path.Combine(Path.GetTempPath(), $"pd-composite-{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        try
        {
            foreach (var file in set.Files)
            {
                if (!file.RelativePath.EndsWith(".h", StringComparison.Ordinal)) continue;
                File.WriteAllText(Path.Combine(dir, file.RelativePath), file.Contents);
            }

            // The bus header: not the runtime, not the shared type declarations (which it includes).
            var headerName = set.Files.Single(f =>
                f.RelativePath.EndsWith(".h", StringComparison.Ordinal) &&
                f.RelativePath != "protodesigner_runtime.h" &&
                !f.RelativePath.EndsWith("_types.h", StringComparison.Ordinal)).RelativePath;

            var (driver, checkCount) = EmitDriver(ir, cases, headerName);
            File.WriteAllText(Path.Combine(dir, "crosscheck.cpp"), driver);

            Assert.True(checkCount > 200, $"Only {checkCount} checks emitted — the matrix has shrunk.");

            var compiler = MsvcLocator.Find();
            Assert.True(compiler is not null || MsvcLocator.SkipRequested,
                "No MSVC toolchain found, so the generated C++ was never compiled — the half of this test "
                + "that actually proves anything did not run. Install the VC++ build tools, or set "
                + $"{MsvcLocator.SkipVariable}=1 to accept generation-only coverage.");

            if (compiler is null) return;   // explicitly opted out above

            var (exitCode, output) = MsvcLocator.CompileAndRun(compiler, dir, "crosscheck.cpp");
            Assert.True(exitCode == 0,
                $"The generated C++ disagreed with the reference codec ({checkCount} checks):\n{output}");
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { /* best effort */ }
        }
    }

    private static (string Source, int Checks) EmitDriver(
        ProtocolIr ir, IReadOnlyList<CompositeMatrix.Case> cases, string headerName)
    {
        var sb = new StringBuilder();
        var checks = 0;

        sb.AppendLine("// Generated by CppCompositeCrossCheck.");
        sb.AppendLine($"#include \"{headerName}\"");
        sb.AppendLine("#include <cstdio>");
        sb.AppendLine("#include <cstring>");
        sb.AppendLine("#include <cmath>");
        sb.AppendLine();
        sb.AppendLine("static int failures = 0;");
        sb.AppendLine();
        sb.AppendLine("static void expect_bytes(const char* where, const uint8_t* got, size_t got_len,");
        sb.AppendLine("                         const uint8_t* want, size_t want_len) {");
        sb.AppendLine("    if (got_len != want_len || memcmp(got, want, want_len) != 0) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        std::printf(\"BYTES %s: got [\", where);");
        sb.AppendLine("        for (size_t i = 0; i < got_len; ++i) std::printf(\"%02X \", got[i]);");
        sb.AppendLine("        std::printf(\"] want [\");");
        sb.AppendLine("        for (size_t i = 0; i < want_len; ++i) std::printf(\"%02X \", want[i]);");
        sb.AppendLine("        std::printf(\"]\\n\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("static void expect_i64(const char* where, int64_t got, int64_t want) {");
        sb.AppendLine("    if (got != want) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        std::printf(\"VALUE %s: got %lld want %lld\\n\", where, (long long)got, (long long)want);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// A quantized value comes back to within half a wire code — that half IS the resolution the");
        sb.AppendLine("// chosen width buys, and claiming better would be claiming the compression was free.");
        sb.AppendLine("static void expect_near(const char* where, double got, double want, double tolerance) {");
        sb.AppendLine("    if (!(std::fabs(got - want) <= tolerance)) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        std::printf(\"NEAR %s: got %.17g want %.17g (tolerance %.17g)\\n\", where, got, want, tolerance);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("static void expect_exact(const char* where, double got, double want) {");
        sb.AppendLine("    if (!(got == want)) {");
        sb.AppendLine("        ++failures;");
        sb.AppendLine("        std::printf(\"EXACT %s: got %.17g want %.17g\\n\", where, got, want);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var c in cases)
        {
            var msg = ir.Messages.Single(m => m.Name == c.Name);
            var structName = CppNaming.TypeName(c.Name);
            sb.AppendLine($"static void check_{structName}() {{");

            switch (c)
            {
                case CompositeMatrix.EnumCase e:
                    checks += EmitEnum(sb, msg, e, structName, ir);
                    break;
                case CompositeMatrix.ArrayCase a:
                    checks += EmitArray(sb, msg, a, structName);
                    break;
                case CompositeMatrix.QuantizedCase q:
                    checks += EmitQuantized(sb, msg, q, structName);
                    break;
                case CompositeMatrix.RawFloatCase r:
                    checks += EmitRawFloat(sb, msg, r, structName);
                    break;
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("int main() {");
        foreach (var c in cases)
            sb.AppendLine($"    check_{CppNaming.TypeName(c.Name)}();");
        sb.AppendLine($"    std::printf(\"%d failure(s) over {checks} checks\\n\", failures);");
        sb.AppendLine("    return failures == 0 ? 0 : 1;");
        sb.AppendLine("}");

        return (sb.ToString(), checks);
    }

    private static void EmitLeadIn(StringBuilder sb, CompositeMatrix.Case c)
    {
        for (var i = 0; i < c.LeadInBits; i++)
            sb.AppendLine($"        m.lead{i} = {(i % 2 == 0 ? 1 : 0)};");
    }

    private static int EmitEnum(
        StringBuilder sb, IrMessage msg, CompositeMatrix.EnumCase e, string structName, ProtocolIr ir)
    {
        var enumName = CppNaming.TypeName($"E_{e.Name}");
        var checks = 0;

        foreach (var value in e.Values)
        {
            var values = CompositeMatrix.BaseValues(e);
            values["value"] = value;
            var expected = Codec.Encode(msg, values);
            var literal = string.Join(", ", expected.Select(b => $"0x{b:X2}"));
            var where = $"{e.Name}@{value}";

            sb.AppendLine("    {");
            sb.AppendLine($"        proto::{structName} m{{}};");
            EmitLeadIn(sb, e);
            sb.AppendLine($"        m.value = static_cast<proto::{enumName}>({value}ll);");
            sb.AppendLine($"        uint8_t wire[proto::{structName}::kMaxBytes];");
            sb.AppendLine($"        size_t n = proto::{structName}_ConvertToWire(m, wire);");
            sb.AppendLine($"        static const uint8_t want[] = {{ {literal} }};");
            sb.AppendLine($"        expect_bytes(\"{where}\", wire, n, want, sizeof(want));");
            sb.AppendLine($"        proto::{structName} back{{}};");
            sb.AppendLine($"        proto::{structName}_ConvertToHost(wire, n, back);");
            sb.AppendLine($"        expect_i64(\"{where}\", static_cast<int64_t>(back.value), {value}ll);");
            sb.AppendLine("    }");
            checks += 2;
        }

        return checks;
    }

    private static int EmitArray(StringBuilder sb, IrMessage msg, CompositeMatrix.ArrayCase a, string structName)
    {
        var elementValues = CompositeMatrix.ArrayElementValues(a);
        var checks = 0;

        // One pass with the boundary values spread across the slots, and one with them reversed, so a
        // stride bug that happens to be symmetric cannot hide.
        foreach (var (label, ordered) in new[]
                 {
                     ("fwd", elementValues.ToList()),
                     ("rev", elementValues.Reverse().ToList()),
                 })
        {
            var slots = Enumerable.Range(0, a.Count).Select(i => ordered[i % ordered.Count]).ToList();

            var values = CompositeMatrix.BaseValues(a);
            values["value"] = slots.Cast<object>().ToList();
            var expected = Codec.Encode(msg, values);
            var literal = string.Join(", ", expected.Select(b => $"0x{b:X2}"));
            var where = $"{a.Name}_{label}";

            sb.AppendLine("    {");
            sb.AppendLine($"        proto::{structName} m{{}};");
            EmitLeadIn(sb, a);
            for (var i = 0; i < slots.Count; i++)
                sb.AppendLine($"        m.value[{i}] = static_cast<{CppNaming.StorageType(a.Element)}>({slots[i]}ll);");
            sb.AppendLine($"        uint8_t wire[proto::{structName}::kMaxBytes];");
            sb.AppendLine($"        size_t n = proto::{structName}_ConvertToWire(m, wire);");
            sb.AppendLine($"        static const uint8_t want[] = {{ {literal} }};");
            sb.AppendLine($"        expect_bytes(\"{where}\", wire, n, want, sizeof(want));");
            sb.AppendLine($"        proto::{structName} back{{}};");
            sb.AppendLine($"        proto::{structName}_ConvertToHost(wire, n, back);");
            for (var i = 0; i < slots.Count; i++)
                sb.AppendLine($"        expect_i64(\"{where}[{i}]\", static_cast<int64_t>(back.value[{i}]), {slots[i]}ll);");
            sb.AppendLine("    }");
            checks += 1 + slots.Count;
        }

        return checks;
    }

    private static int EmitQuantized(
        StringBuilder sb, IrMessage msg, CompositeMatrix.QuantizedCase q, string structName)
    {
        var field = msg.Fields.Single(f => f.Path == "value");
        var step = (double)field.Transform.Scale;
        var checks = 0;

        foreach (var value in CompositeMatrix.QuantizedValues(q))
        {
            var values = CompositeMatrix.BaseValues(q);
            values["value"] = value;
            var expected = Codec.Encode(msg, values);
            var literal = string.Join(", ", expected.Select(b => $"0x{b:X2}"));
            var where = $"{q.Name}@{CompositeMatrix.Dec(value)}";

            // Two sources of slack on top of the half-code quantization error. An integer host rounds the
            // decoded value to a whole number, costing up to another half unit. An F32 host cannot hold
            // the value exactly in the first place.
            var isIntegerHost = q.Host is not (PrimitiveKind.F32 or PrimitiveKind.F64);
            var slack = isIntegerHost ? 0.5 + 1e-9
                : q.Host == PrimitiveKind.F32 ? step * 0.01 + 1e-4
                : 1e-9;

            sb.AppendLine("    {");
            sb.AppendLine($"        proto::{structName} m{{}};");
            EmitLeadIn(sb, q);
            sb.AppendLine($"        m.value = static_cast<{CppNaming.StorageType(q.Host)}>({D(value)});");
            sb.AppendLine($"        uint8_t wire[proto::{structName}::kMaxBytes];");
            sb.AppendLine($"        size_t n = proto::{structName}_ConvertToWire(m, wire);");
            sb.AppendLine($"        static const uint8_t want[] = {{ {literal} }};");
            sb.AppendLine($"        expect_bytes(\"{where}\", wire, n, want, sizeof(want));");
            sb.AppendLine($"        proto::{structName} back{{}};");
            sb.AppendLine($"        proto::{structName}_ConvertToHost(wire, n, back);");
            sb.AppendLine($"        expect_near(\"{where}\", static_cast<double>(back.value), {D(value)}, {Lit(step / 2 + slack)});");
            sb.AppendLine("    }");
            checks += 2;
        }

        return checks;
    }

    private static int EmitRawFloat(
        StringBuilder sb, IrMessage msg, CompositeMatrix.RawFloatCase r, string structName)
    {
        var checks = 0;

        foreach (var value in CompositeMatrix.RawFloatValues(r))
        {
            var values = CompositeMatrix.BaseValues(r);
            // Narrow to the host width first, so both sides start from the same number rather than from
            // two different roundings of the literal. Passed as a double: a raw IEEE field carries values
            // outside decimal's range entirely.
            values["value"] = r.Host == PrimitiveKind.F32 ? (double)(float)value : value;

            var expected = Codec.Encode(msg, values);
            var literal = string.Join(", ", expected.Select(b => $"0x{b:X2}"));
            var where = $"{r.Name}@{value.ToString("R", CultureInfo.InvariantCulture)}";

            sb.AppendLine("    {");
            sb.AppendLine($"        proto::{structName} m{{}};");
            EmitLeadIn(sb, r);
            sb.AppendLine($"        m.value = static_cast<{CppNaming.StorageType(r.Host)}>({Lit(value)});");
            sb.AppendLine($"        uint8_t wire[proto::{structName}::kMaxBytes];");
            sb.AppendLine($"        size_t n = proto::{structName}_ConvertToWire(m, wire);");
            sb.AppendLine($"        static const uint8_t want[] = {{ {literal} }};");
            sb.AppendLine($"        expect_bytes(\"{where}\", wire, n, want, sizeof(want));");
            sb.AppendLine($"        proto::{structName} back{{}};");
            sb.AppendLine($"        proto::{structName}_ConvertToHost(wire, n, back);");
            // Raw means raw: the bit pattern went out untouched, so it must come back identical.
            sb.AppendLine($"        expect_exact(\"{where}\", static_cast<double>(back.value), " +
                          $"static_cast<double>(static_cast<{CppNaming.StorageType(r.Host)}>({Lit(value)})));");
            sb.AppendLine("    }");
            checks += 2;
        }

        return checks;
    }

    private static string D(decimal value) => Lit((double)value);

    /// <summary>A C++ double literal that round-trips back to the same double.</summary>
    private static string Lit(double value)
    {
        var text = value.ToString("R", CultureInfo.InvariantCulture);
        if (text.IndexOf('.') < 0 && text.IndexOf('E') < 0 && text.IndexOf('e') < 0) text += ".0";
        return text;
    }
}
