using System.Globalization;
using System.Text;
using ProtoDesigner.Core.Ir;
using ProtoDesigner.Core.Model;

namespace ProtoDesigner.CodeGen.Cpp;

/// <summary>
/// Emits C++14 conversion code for a protocol. Output is a fixed runtime header plus one header per bus
/// holding an enum per IR enum, a struct per message in its <em>host</em> representation, and the two
/// conversions between that struct and the wire: <c>ConvertToWire(host, wire, cap)</c> and
/// <c>ConvertToHost(wire, len, host)</c>.
/// </summary>
/// <remarks>
/// Offsets inside a <see cref="IrRegionKind.Fixed"/> region are emitted as compile-time constants.
/// A <see cref="IrRegionKind.Variable"/> region runs a cursor for its elements only; the fixed region
/// that follows it goes back to constant offsets relative to where the variable part ended. That is
/// the whole point of the region model.
/// </remarks>
public sealed class CppGenerator : IProtocolGenerator
{
    public string Id => "cpp";

    public string DisplayName => "C++14";

    public GeneratedFileSet Generate(ProtocolIr ir, GeneratorOptions options)
    {
        ArgumentNullException.ThrowIfNull(ir);
        options ??= new GeneratorOptions();

        var files = new List<GeneratedFile>
        {
            new(CppRuntimeHeader.FileName, CppRuntimeHeader.Emit()),
            new($"{FileStem(ir.BusName)}.h", EmitProtocolHeader(ir, options)),
        };

        if (options.IncludeReadme)
            files.Add(new("README.md", EmitReadme(ir, options)));

        return new GeneratedFileSet(files);
    }

    private static string FileStem(string busName) =>
        CppNaming.TypeName(busName).ToLowerInvariant();

    // ---- protocol header ----------------------------------------------------------------------

    private static string EmitProtocolHeader(ProtocolIr ir, GeneratorOptions options)
    {
        var ns = CppNaming.TypeName(options.Namespace).ToLowerInvariant();
        var guard = $"PROTODESIGNER_{CppNaming.TypeName(ir.BusName).ToUpperInvariant()}_H";
        var sb = new StringBuilder();

        sb.AppendLine("// -----------------------------------------------------------------------------");
        sb.AppendLine($"// {ir.ProjectName} — bus '{ir.BusName}' ({ir.Transport})");
        sb.AppendLine("// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.");
        sb.AppendLine("// -----------------------------------------------------------------------------");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine($"#include \"{CppRuntimeHeader.FileName}\"");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns} {{");
        sb.AppendLine();

        foreach (var e in ir.Enums) EmitEnum(sb, e);
        foreach (var m in ir.Messages) EmitMessage(sb, ir, m);

        sb.AppendLine($"}} // namespace {ns}");
        sb.AppendLine();
        sb.AppendLine($"#endif // {guard}");
        return sb.ToString();
    }

    private static void EmitEnum(StringBuilder sb, IrEnum e)
    {
        var name = CppNaming.TypeName(e.Name);
        var storage = CppNaming.StorageType(e.Underlying);

        sb.AppendLine($"// {(e.IsFlags ? "Flag set" : "Enumeration")} '{e.Name}'.");
        sb.AppendLine($"enum class {name} : {storage} {{");
        foreach (var m in e.Members)
            sb.AppendLine($"    {CppNaming.EnumMemberName(m.Name)} = {m.Value.ToString(CultureInfo.InvariantCulture)},");
        sb.AppendLine("};");
        sb.AppendLine();
    }

    private static void EmitMessage(StringBuilder sb, ProtocolIr ir, IrMessage m)
    {
        var name = CppNaming.TypeName(m.Name);

        // ---- struct ----
        sb.AppendLine($"// Message '{m.Name}'"
            + (m.WireId is { } w ? $" (wire id {w})" : "")
            + (m.MinBits == m.MaxBits
                ? $" — fixed {m.MinBits} bits / {(m.MinBits + 7) / 8} bytes."
                : $" — {m.MinBits}..{m.MaxBits} bits / {(m.MinBits + 7) / 8}..{(m.MaxBits + 7) / 8} bytes."));
        sb.AppendLine($"struct {name} {{");
        if (m.WireId is { } wireId)
            sb.AppendLine($"    static constexpr uint32_t kWireId = {wireId}u;");
        sb.AppendLine($"    static constexpr size_t kMinBits  = {m.MinBits};");
        sb.AppendLine($"    static constexpr size_t kMaxBits  = {m.MaxBits};");
        sb.AppendLine($"    static constexpr size_t kMaxBytes = {(m.MaxBits + 7) / 8};");
        sb.AppendLine();

        foreach (var f in m.Fields) EmitMember(sb, ir, f);

        sb.AppendLine("};");
        sb.AppendLine();

        EmitEncode(sb, ir, m, name);
        EmitDecode(sb, ir, m, name);
    }

    private static void EmitMember(StringBuilder sb, ProtocolIr ir, IrField f)
    {
        var member = CppNaming.MemberName(f.Path);

        if (f.Kind == IrFieldKind.Array && f.Array is { } arr)
        {
            var elemType = arr.ElementEnumIndex is { } ei
                ? CppNaming.TypeName(ir.Enums[ei].Name)
                : CppNaming.StorageType(arr.ElementPrimitive);

            sb.AppendLine($"    // '{f.Path}': {DescribeArray(arr)}, {arr.ElementBits} bits per element");
            sb.AppendLine($"    {elemType} {member}[{arr.MaxElements}];");

            // A Fixed array's length is a constant, and a CountFromField array's length already lives
            // in its count field — emitting a second copy would let the two disagree and silently
            // desynchronise the encoder from the wire. Only self-describing arrays get their own count.
            if (arr.Kind is not (IrArrayKind.Fixed or IrArrayKind.CountFromField))
                sb.AppendLine($"    uint32_t {member}_count;");
            return;
        }

        var type = f.Kind == IrFieldKind.EnumRef && f.EnumIndex is { } idx
            ? CppNaming.TypeName(ir.Enums[idx].Name)
            : CppNaming.StorageType(f.Primitive);

        string note;
        if (IsRawFloat(f.Primitive, f.Transform))
            note = $"{f.BitWidth} bits, raw IEEE-754";
        else if (f.Transform.IsIdentity)
            note = $"{f.BitWidth} bits";
        else
            note = $"{f.BitWidth} bits, wire = (value {Signed(-f.Transform.Offset)}) / {Dec(f.Transform.Scale)}";

        sb.AppendLine($"    {type} {member};   // {note}");
    }

    private static string DescribeArray(IrArrayInfo arr) => arr.Kind switch
    {
        IrArrayKind.Fixed => $"exactly {arr.ElementCount} elements",
        IrArrayKind.CountFromField => $"up to {arr.MaxElements}, count from an earlier field",
        IrArrayKind.LengthPrefixed => $"up to {arr.MaxElements}, {arr.PrefixBits}-bit length prefix",
        IrArrayKind.Terminated => $"up to {arr.MaxElements}, sentinel-terminated",
        IrArrayKind.FillRemaining => $"up to {arr.MaxElements}, fills the frame",
        _ => "array",
    };

    // ---- encode -------------------------------------------------------------------------------

    private static void EmitEncode(StringBuilder sb, ProtocolIr ir, IrMessage m, string structName)
    {
        sb.AppendLine($"// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).");
        sb.AppendLine("// Returns the number of bytes written, or 0 if the buffer was too small.");
        sb.AppendLine($"inline size_t ConvertToWire(const {structName}& msg, uint8_t* wire, size_t cap) {{");
        sb.AppendLine("    protodesigner::BitWriter w(wire, cap);");

        foreach (var region in m.Regions)
        {
            var fields = m.Fields.Where(f => f.RegionIndex == region.Index).ToList();
            if (fields.Count == 0 && region.Kind == IrRegionKind.Fixed) continue;

            sb.AppendLine();
            sb.AppendLine($"    // --- region {region.Index} ({region.Kind}) ---");
            sb.AppendLine($"    const size_t r{region.Index} = w.bit_length();");

            foreach (var f in fields)
            {
                sb.AppendLine($"    // {f.Path}");
                sb.AppendLine($"    if (w.bit_length() < r{region.Index} + {f.BitOffset}) w.skip(r{region.Index} + {f.BitOffset} - w.bit_length());");
                EmitEncodeField(sb, ir, m, f);
            }

            if (region.Kind == IrRegionKind.Fixed)
                sb.AppendLine("    w.pad_to(8);");
        }

        sb.AppendLine();
        sb.AppendLine("    if (w.overflowed()) return 0;");
        sb.AppendLine("    return w.byte_length();");
        sb.AppendLine("}");
        sb.AppendLine();

        // Reference-to-array overload: the capacity comes from the type, so it cannot be passed wrongly
        // and a buffer that is too small is a compile error rather than a runtime zero.
        sb.AppendLine($"// Same conversion into a correctly sized array. The capacity is checked at compile time.");
        sb.AppendLine($"inline size_t ConvertToWire(const {structName}& msg, uint8_t (&wire)[{structName}::kMaxBytes]) {{");
        sb.AppendLine($"    return ConvertToWire(msg, wire, {structName}::kMaxBytes);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitEncodeField(StringBuilder sb, ProtocolIr ir, IrMessage m, IrField f)
    {
        var member = CppNaming.MemberName(f.Path);
        var endian = EndianExpr(f.Endianness);

        if (f.Kind == IrFieldKind.Array && f.Array is { } arr)
        {
            var countExpr = arr.Kind switch
            {
                IrArrayKind.Fixed => arr.ElementCount!.Value.ToString(CultureInfo.InvariantCulture),
                // The count field is the single source of truth — read it, don't shadow it.
                IrArrayKind.CountFromField when arr.CountFieldIndex is { } ci =>
                    $"msg.{CppNaming.MemberName(m.Fields[ci].Path)}",
                _ => $"msg.{member}_count",
            };

            if (arr.Kind == IrArrayKind.LengthPrefixed)
                sb.AppendLine($"    w.write_unsigned(static_cast<uint64_t>({countExpr}), {arr.PrefixBits}, protodesigner::Endian::Little);");

            sb.AppendLine($"    for (size_t i = 0; i < static_cast<size_t>({countExpr}) && i < {arr.MaxElements}; ++i) {{");
            var elemAccess = arr.ElementEnumIndex is not null
                ? $"static_cast<int64_t>(msg.{member}[i])"
                : $"msg.{member}[i]";
            var elemWire = IsRawFloat(arr.ElementPrimitive, f.Transform)
                ? (arr.ElementPrimitive == PrimitiveKind.F32
                    ? $"protodesigner::float_bits(msg.{member}[i])"
                    : $"protodesigner::double_bits(msg.{member}[i])")
                : ToWireCode(elemAccess, f.Transform, arr.ElementPrimitive);
            if (IsRawFloat(arr.ElementPrimitive, f.Transform))
                sb.AppendLine($"        w.write_unsigned(static_cast<uint64_t>({elemWire}), {arr.ElementBits}, {endian});");
            else if (IsSigned(arr.ElementPrimitive))
                sb.AppendLine($"        w.write_signed(static_cast<int64_t>({elemWire}), {arr.ElementBits}, {endian});");
            else
                sb.AppendLine($"        w.write_unsigned(static_cast<uint64_t>({elemWire}), {arr.ElementBits}, {endian});");
            sb.AppendLine("    }");

            if (arr.Kind == IrArrayKind.Terminated && arr.Sentinel.Count > 0)
            {
                var bytes = string.Join(", ", arr.Sentinel.Select(b => $"0x{b:X2}"));
                sb.AppendLine($"    {{ static const uint8_t kSentinel[] = {{ {bytes} }}; w.write_bytes(kSentinel, {arr.Sentinel.Count}); }}");
            }
            return;
        }

        // A float host with no transform means the IEEE bit pattern goes on the wire verbatim. Casting
        // the value to an integer instead would keep 3 of 3.14159 and throw the rest away.
        if (IsRawFloat(f.Primitive, f.Transform))
        {
            var bitsCall = f.Primitive == PrimitiveKind.F32
                ? $"protodesigner::float_bits(msg.{member})"
                : $"protodesigner::double_bits(msg.{member})";
            sb.AppendLine($"    w.write_unsigned(static_cast<uint64_t>({bitsCall}), {f.BitWidth}, {endian});");
            return;
        }

        var access = f.Kind == IrFieldKind.EnumRef
            ? $"static_cast<int64_t>(msg.{member})"
            : $"msg.{member}";
        var wire = ToWireCode(access, f.Transform, f.Primitive);

        if (IsSigned(f.Primitive))
            sb.AppendLine($"    w.write_signed(static_cast<int64_t>({wire}), {f.BitWidth}, {endian});");
        else
            sb.AppendLine($"    w.write_unsigned(static_cast<uint64_t>({wire}), {f.BitWidth}, {endian});");
    }

    // ---- decode -------------------------------------------------------------------------------

    private static void EmitDecode(StringBuilder sb, ProtocolIr ir, IrMessage m, string structName)
    {
        sb.AppendLine($"// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.");
        sb.AppendLine("// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.");
        sb.AppendLine($"inline protodesigner::DecodeResult ConvertToHost(const uint8_t* wire, size_t len, {structName}& msg) {{");
        sb.AppendLine("    protodesigner::BitReader r(wire, len);");

        foreach (var region in m.Regions)
        {
            var fields = m.Fields.Where(f => f.RegionIndex == region.Index).ToList();
            if (fields.Count == 0 && region.Kind == IrRegionKind.Fixed) continue;

            sb.AppendLine();
            sb.AppendLine($"    // --- region {region.Index} ({region.Kind}) ---");
            sb.AppendLine($"    const size_t r{region.Index} = r.bit_offset();");

            foreach (var f in fields)
            {
                sb.AppendLine($"    // {f.Path}");
                sb.AppendLine($"    if (r.bit_offset() < r{region.Index} + {f.BitOffset}) r.skip(r{region.Index} + {f.BitOffset} - r.bit_offset());");
                EmitDecodeField(sb, ir, m, f);
            }

            if (region.Kind == IrRegionKind.Fixed)
                sb.AppendLine("    r.align_to(8);");
        }

        sb.AppendLine();
        sb.AppendLine("    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());");
        sb.AppendLine("    return protodesigner::DecodeResult::Ok();");
        sb.AppendLine("}");
        sb.AppendLine();

        // Only a fixed-size message gets the array overload. For a variable-size one the array length is
        // the maximum, not what arrived, so the caller must say how many bytes the frame actually held.
        if (m.MinBits == m.MaxBits)
        {
            sb.AppendLine($"// Same conversion from a full frame. Fixed-size message, so the length is implied.");
            sb.AppendLine($"inline protodesigner::DecodeResult ConvertToHost(const uint8_t (&wire)[{structName}::kMaxBytes], {structName}& msg) {{");
            sb.AppendLine($"    return ConvertToHost(wire, {structName}::kMaxBytes, msg);");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static void EmitDecodeField(StringBuilder sb, ProtocolIr ir, IrMessage m, IrField f)
    {
        var member = CppNaming.MemberName(f.Path);
        var endian = EndianExpr(f.Endianness);

        if (f.Kind == IrFieldKind.Array && f.Array is { } arr)
        {
            string countExpr;
            switch (arr.Kind)
            {
                case IrArrayKind.Fixed:
                    countExpr = arr.ElementCount!.Value.ToString(CultureInfo.InvariantCulture);
                    break;
                case IrArrayKind.CountFromField when arr.CountFieldIndex is { } ci:
                    // The count field was decoded earlier in this same message; read it directly.
                    countExpr = $"msg.{CppNaming.MemberName(m.Fields[ci].Path)}";
                    break;
                case IrArrayKind.LengthPrefixed:
                    sb.AppendLine($"    msg.{member}_count = static_cast<uint32_t>(r.read_unsigned({arr.PrefixBits}, protodesigner::Endian::Little));");
                    countExpr = $"msg.{member}_count";
                    break;
                default:
                    sb.AppendLine($"    // {arr.Kind} arrays consume the remainder; the caller supplies the count.");
                    countExpr = $"msg.{member}_count";
                    break;
            }

            sb.AppendLine($"    for (size_t i = 0; i < static_cast<size_t>({countExpr}) && i < {arr.MaxElements}; ++i) {{");
            var elemType = arr.ElementEnumIndex is { } ei
                ? CppNaming.TypeName(ir.Enums[ei].Name)
                : CppNaming.StorageType(arr.ElementPrimitive);

            if (IsRawFloat(arr.ElementPrimitive, f.Transform))
            {
                var fromBits = arr.ElementPrimitive == PrimitiveKind.F32
                    ? $"protodesigner::bits_to_float(static_cast<uint32_t>(r.read_unsigned({arr.ElementBits}, {endian})))"
                    : $"protodesigner::bits_to_double(static_cast<uint64_t>(r.read_unsigned({arr.ElementBits}, {endian})))";
                sb.AppendLine($"        msg.{member}[i] = {fromBits};");
            }
            else
            {
                var readCall = IsSigned(arr.ElementPrimitive)
                    ? $"r.read_signed({arr.ElementBits}, {endian})"
                    : $"r.read_unsigned({arr.ElementBits}, {endian})";
                var fromWire = FromWireCode(readCall, f.Transform, arr.ElementPrimitive);
                sb.AppendLine($"        msg.{member}[i] = static_cast<{elemType}>({fromWire});");
            }
            sb.AppendLine("    }");

            if (arr.Kind == IrArrayKind.Terminated && arr.Sentinel.Count > 0)
                sb.AppendLine($"    r.skip({arr.Sentinel.Count * 8});   // sentinel");
            return;
        }

        if (IsRawFloat(f.Primitive, f.Transform))
        {
            var fromBits = f.Primitive == PrimitiveKind.F32
                ? $"protodesigner::bits_to_float(static_cast<uint32_t>(r.read_unsigned({f.BitWidth}, {endian})))"
                : $"protodesigner::bits_to_double(static_cast<uint64_t>(r.read_unsigned({f.BitWidth}, {endian})))";
            sb.AppendLine($"    msg.{member} = {fromBits};");
            return;
        }

        var call = IsSigned(f.Primitive)
            ? $"r.read_signed({f.BitWidth}, {endian})"
            : $"r.read_unsigned({f.BitWidth}, {endian})";
        var value = FromWireCode(call, f.Transform, f.Primitive);
        var type = f.Kind == IrFieldKind.EnumRef && f.EnumIndex is { } idx
            ? CppNaming.TypeName(ir.Enums[idx].Name)
            : CppNaming.StorageType(f.Primitive);

        sb.AppendLine($"    msg.{member} = static_cast<{type}>({value});");
    }

    // ---- transform helpers ---------------------------------------------------------------------

    /// <summary>
    /// <c>wire = (value - offset) / scale</c>, wrapped in a round-to-nearest when the maths is
    /// floating-point.
    /// </summary>
    /// <remarks>
    /// The rounding is not cosmetic. Assigning a <c>double</c> to an integer truncates toward zero, so a
    /// -40..70 field scaled by 110/255 turns 70.0 into 254.99999999999997 and stores 254 — the top code
    /// the width was chosen for is never reached, and every other reading is biased low by up to a full
    /// code. Integer pipelines are left alone: forcing them through a <c>double</c> would lose precision
    /// above 2^53 for no gain.
    /// </remarks>
    private static string ToWireCode(string valueExpr, ScalarTransform t, PrimitiveKind host)
    {
        if (t.IsIdentity) return valueExpr;

        var expr = valueExpr;
        if (t.Offset != 0m) expr = $"(({expr}) {Signed(-t.Offset)})";
        if (t.Scale != 1m) expr = $"(({expr}) / {Dec(t.Scale)})";

        return IsFloatingMath(t, host) ? $"protodesigner::quantize({expr})" : expr;
    }

    /// <summary><c>value = (wire * scale) + offset</c>.</summary>
    private static string FromWireCode(string wireExpr, ScalarTransform t, PrimitiveKind host)
    {
        if (t.IsIdentity) return wireExpr;

        var expr = wireExpr;
        if (t.Scale != 1m) expr = $"(({expr}) * {Dec(t.Scale)})";
        if (t.Offset != 0m) expr = $"(({expr}) {Signed(t.Offset)})";

        // Coming back the other way, a float host keeps the fractional part — that IS the decoded value —
        // so only an integer host needs the result rounded rather than truncated.
        return IsFloatingMath(t, host) && !IsFloat(host) ? $"protodesigner::quantize({expr})" : expr;
    }

    /// <summary>
    /// Whether the emitted expression is evaluated in floating point: either the host is a float, or the
    /// scale is fractional and drags the whole expression into <c>double</c>.
    /// </summary>
    private static bool IsFloatingMath(ScalarTransform t, PrimitiveKind host) =>
        IsFloat(host) || decimal.Truncate(t.Scale) != t.Scale;

    /// <summary>
    /// A float host with no transform: the IEEE bit pattern goes on the wire untouched. The propagator
    /// guarantees the pairing — a float wire form produces no transform, and any integer wire form on a
    /// float host always produces one.
    /// </summary>
    private static bool IsRawFloat(PrimitiveKind host, ScalarTransform t) => IsFloat(host) && t.IsIdentity;

    private static bool IsFloat(PrimitiveKind kind) => kind is PrimitiveKind.F32 or PrimitiveKind.F64;

    /// <summary>Renders a term as <c>+ n</c> or <c>- n</c>, so an offset of -40 reads `+ 40`, not `- -40`.</summary>
    private static string Signed(decimal value) =>
        value < 0m ? $"- {Dec(-value)}" : $"+ {Dec(value)}";

    /// <summary>
    /// Emits a transform constant as a C++ literal.
    /// </summary>
    /// <remarks>
    /// Integral values stay integral so an otherwise-integer pipeline is not forced into floating-point
    /// maths. Everything else becomes a <c>double</c> literal — never a <c>float</c> one. A derived scale
    /// is <c>(max - min) / (2^bits - 1)</c>, which carries far more significant digits than float's ~7:
    /// rounding 110/255 down to float puts the top of a -40..70 range at 254.99999 of 255 codes, and the
    /// cast to an integer then truncates it to 254. The whole top of the range would be off by one.
    /// </remarks>
    private static string Dec(decimal value)
    {
        if (decimal.Truncate(value) == value && Math.Abs(value) < 1e18m)
            return decimal.ToInt64(value).ToString(CultureInfo.InvariantCulture);

        // "R" gives the shortest form that round-trips back to the same double, so the emitted constant
        // names exactly the double the C# side would compute from the same decimal.
        var text = ((double)value).ToString("R", CultureInfo.InvariantCulture);

        // A decimal that is only just non-integral can still land on a whole double; without a decimal
        // point that would emit as an int literal and silently switch the expression to integer maths.
        if (text.IndexOf('.') < 0 && text.IndexOf('E') < 0 && text.IndexOf('e') < 0)
            text += ".0";
        return text;
    }

    private static string EndianExpr(Endianness e) =>
        e == Endianness.Big ? "protodesigner::Endian::Big" : "protodesigner::Endian::Little";

    private static bool IsSigned(PrimitiveKind kind) =>
        kind is PrimitiveKind.I8 or PrimitiveKind.I16 or PrimitiveKind.I32 or PrimitiveKind.I64;

    // ---- readme --------------------------------------------------------------------------------

    private static string EmitReadme(ProtocolIr ir, GeneratorOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {ir.ProjectName} — `{ir.BusName}` C++ codec");
        sb.AppendLine();
        sb.AppendLine("Generated by ProtoDesigner. Do not edit these files; change the `.pdproj` and regenerate.");
        sb.AppendLine();
        sb.AppendLine($"- Transport: **{ir.Transport}**");
        sb.AppendLine($"- Namespace: `{CppNaming.TypeName(options.Namespace).ToLowerInvariant()}`");
        sb.AppendLine($"- Standard: C++14, header-only, no allocation, no exceptions");
        sb.AppendLine();
        sb.AppendLine("## Messages");
        sb.AppendLine();
        sb.AppendLine("| Message | Wire id | Size | Fields |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var m in ir.Messages)
        {
            var size = m.MinBits == m.MaxBits
                ? $"{(m.MinBits + 7) / 8} B"
                : $"{(m.MinBits + 7) / 8}–{(m.MaxBits + 7) / 8} B";
            sb.AppendLine($"| `{CppNaming.TypeName(m.Name)}` | {(m.WireId?.ToString(CultureInfo.InvariantCulture) ?? "—")} | {size} | {m.Fields.Count} |");
        }
        sb.AppendLine();
        sb.AppendLine("## Usage");
        sb.AppendLine();
        sb.AppendLine("```cpp");
        var first = ir.Messages.FirstOrDefault();
        var typeName = first is null ? "Message" : CppNaming.TypeName(first.Name);
        var nsName = CppNaming.TypeName(options.Namespace).ToLowerInvariant();
        sb.AppendLine($"#include \"{FileStem(ir.BusName)}.h\"");
        sb.AppendLine();
        sb.AppendLine($"// The struct is the HOST representation: plain fields, no packing, no scaling.");
        sb.AppendLine($"{nsName}::{typeName} msg{{}};");
        sb.AppendLine("// ... populate msg ...");
        sb.AppendLine();
        sb.AppendLine("// Host -> wire.");
        sb.AppendLine($"uint8_t wire[{nsName}::{typeName}::kMaxBytes];");
        sb.AppendLine($"size_t written = {nsName}::ConvertToWire(msg, wire);   // or (msg, wire, sizeof(wire))");
        sb.AppendLine("if (written == 0) { /* buffer too small */ }");
        sb.AppendLine();
        sb.AppendLine("// Wire -> host.");
        sb.AppendLine($"{nsName}::{typeName} parsed{{}};");
        sb.AppendLine($"auto status = {nsName}::ConvertToHost(wire, written, parsed);");
        sb.AppendLine("if (!status.ok) { /* truncated frame */ }");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Conversions");
        sb.AppendLine();
        sb.AppendLine("| | Signature | Returns |");
        sb.AppendLine("|---|---|---|");
        sb.AppendLine("| Host → wire | `ConvertToWire(const Msg&, uint8_t* wire, size_t cap)` | bytes written, `0` on overflow |");
        sb.AppendLine("| Host → wire | `ConvertToWire(const Msg&, uint8_t (&wire)[Msg::kMaxBytes])` | bytes written |");
        sb.AppendLine("| Wire → host | `ConvertToHost(const uint8_t* wire, size_t len, Msg&)` | `DecodeResult` |");
        sb.AppendLine("| Wire → host | `ConvertToHost(const uint8_t (&wire)[Msg::kMaxBytes], Msg&)` | `DecodeResult` (fixed-size messages only) |");
        return sb.ToString();
    }
}
