/* -----------------------------------------------------------------------------
   BiasedSignedSample - bus 'Attitude' (Uart)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_ATTITUDE_H
#define PROTODESIGNER_ATTITUDE_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Attitude' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_AttitudeMessageId {
    proto_AttitudeMessageId_NotAssigned = 0,
    proto_AttitudeMessageId_Angles = 4,
} proto_AttitudeMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_AttitudeMessageId proto_Attitude_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 4u: return proto_AttitudeMessageId_Angles;
        default: break;
    }
    return proto_AttitudeMessageId_NotAssigned;
}

/* Message 'Angles' (wire id 4) - fixed 8 bits / 1 bytes. */
#define PROTO_ANGLES_WIRE_ID 4u
#define PROTO_ANGLES_MAX_BYTES 1

typedef struct proto_Angles {
    int16_t tilt;   /* 8 bits */
} proto_Angles;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Angles_OnWireLength(const proto_Angles* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_ANGLES_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_ANGLES_MAX_BYTES]. */
PD_INLINE size_t proto_Angles_ConvertToWire(const proto_Angles* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* tilt */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(pd_quantize(((((msg->tilt) + 100)) / 0.784313725490196))), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Angles_ConvertToHost(const uint8_t* wire, size_t len, proto_Angles* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* tilt */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->tilt = (int16_t)(pd_quantize(((((pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST)) * 0.784313725490196)) - 100)));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_ATTITUDE_H */
