// -----------------------------------------------------------------------------
// BiasedSignedSample — bus 'Attitude' (Uart)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_ATTITUDE_H
#define PROTODESIGNER_ATTITUDE_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Attitude' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class AttitudeMessageId : uint32_t {
    NotAssigned = 0,
    Angles = 4u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline AttitudeMessageId Attitude_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 4u: return AttitudeMessageId::Angles;
        default: break;
    }
    return AttitudeMessageId::NotAssigned;
}

// Message 'Angles' (wire id 4) — fixed 8 bits / 1 bytes.
struct Angles {
    static constexpr uint32_t kWireId = 4u;
    static constexpr size_t kMinBits  = 8;
    static constexpr size_t kMaxBits  = 8;
    static constexpr size_t kMaxBytes = 1;

    int16_t tilt;   // 8 bits
};

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Angles_ConvertToWire(const Angles& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // tilt
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(protodesigner::quantize(((((msg.tilt) + 100)) / 0.784313725490196))), 8, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Angles_ConvertToWire(const Angles& msg, uint8_t (&wire)[Angles::kMaxBytes]) {
    return Angles_ConvertToWire(msg, wire, Angles::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Angles_ConvertToHost(const uint8_t* wire, size_t len, Angles& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // tilt
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.tilt = static_cast<int16_t>(protodesigner::quantize(((((r.read_unsigned(8, protodesigner::Endian::Little)) * 0.784313725490196)) - 100)));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Angles_ConvertToHost(const uint8_t (&wire)[Angles::kMaxBytes], Angles& msg) {
    return Angles_ConvertToHost(wire, Angles::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_ATTITUDE_H
