// -----------------------------------------------------------------------------
// DynamicSample — bus 'Bulk' (Ethernet)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_BULK_H
#define PROTODESIGNER_BULK_H

#include "protodesigner_runtime.h"

namespace proto {

// Message 'Batch' (wire id 21) — 24..280 bits / 3..35 bytes.
struct Batch {
    static constexpr uint32_t kWireId = 21u;
    static constexpr size_t kMinBits  = 24;
    static constexpr size_t kMaxBits  = 280;
    static constexpr size_t kMaxBytes = 35;

    uint8_t count;   // 8 bits
    // 'payload': up to 32, count from an earlier field, 8 bits per element
    uint8_t payload[32];
    uint16_t crc;   // 16 bits
};

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t ConvertToWire(const Batch& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // count
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.count), 8, protodesigner::Endian::Little);
    w.pad_to(8);

    // --- region 1 (Variable) ---
    const size_t r1 = w.bit_length();
    // payload
    if (w.bit_length() < r1 + 0) w.skip(r1 + 0 - w.bit_length());
    for (size_t i = 0; i < static_cast<size_t>(msg.count) && i < 32; ++i) {
        w.write_unsigned(static_cast<uint64_t>(msg.payload[i]), 8, protodesigner::Endian::Little);
    }

    // --- region 2 (Fixed) ---
    const size_t r2 = w.bit_length();
    // crc
    if (w.bit_length() < r2 + 0) w.skip(r2 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.crc), 16, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t ConvertToWire(const Batch& msg, uint8_t (&wire)[Batch::kMaxBytes]) {
    return ConvertToWire(msg, wire, Batch::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult ConvertToHost(const uint8_t* wire, size_t len, Batch& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // count
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.count = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    r.align_to(8);

    // --- region 1 (Variable) ---
    const size_t r1 = r.bit_offset();
    // payload
    if (r.bit_offset() < r1 + 0) r.skip(r1 + 0 - r.bit_offset());
    for (size_t i = 0; i < static_cast<size_t>(msg.count) && i < 32; ++i) {
        msg.payload[i] = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    }

    // --- region 2 (Fixed) ---
    const size_t r2 = r.bit_offset();
    // crc
    if (r.bit_offset() < r2 + 0) r.skip(r2 + 0 - r.bit_offset());
    msg.crc = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Little));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

} // namespace proto

#endif // PROTODESIGNER_BULK_H
