// -----------------------------------------------------------------------------
// DynamicSample — bus 'Bulk' (Ethernet)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_BULK_H
#define PROTODESIGNER_BULK_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Bulk' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class BulkMessageId : uint32_t {
    NotAssigned = 0,
    Batch = 21u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline BulkMessageId Bulk_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 21u: return BulkMessageId::Batch;
        default: break;
    }
    return BulkMessageId::NotAssigned;
}

// Message 'Batch' (wire id 21) — 24..280 bits / 3..35 bytes.
struct Batch {
    static constexpr uint32_t kWireId = 21u;
    static constexpr size_t kMaxBytes = 35;

    uint8_t count;
    // 'payload': up to 32, count from an earlier field
    uint8_t payload[32];
    uint16_t crc;
};

// The number of bytes this message occupies on the wire.
// Variable-length: the count carried by each dynamic array decides the total.
inline size_t Batch_OnWireLength(const Batch& msg) {
    size_t bits = 0;
    bits += 8;                 // region 0 (Fixed)
    bits = ((bits + 7) / 8) * 8;   // the encoder pads each fixed region to a byte
    {   // region 1 (Variable), up to 32 x 8 bits
        size_t n = static_cast<size_t>(msg.count);
        if (n > 32) n = 32;   // the encoder truncates at capacity
        bits += n * 8;
    }
    bits += 16;                 // region 2 (Fixed)
    bits = ((bits + 7) / 8) * 8;   // the encoder pads each fixed region to a byte
    return (bits + 7) / 8;
}

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Batch_ConvertToWire(const Batch& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // count
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.count), 8, protodesigner::Endian::Little);
    w.pad_to(8);

    // --- region 1 (Variable) ---
    const size_t r1 = w.bit_length();
    // payload
    if (w.bit_length() < r1 + 0) w.skip(r1 + 0 - w.bit_length());
    for (size_t i = 0; i < static_cast<size_t>(msg.count) && i < 32; ++i) {
        w.write_unsigned(static_cast<uint64_t>(msg.payload[i]), 8, protodesigner::Endian::Little);
    }

    // --- region 2 (Fixed) ---
    const size_t r2 = w.bit_length();
    // crc
    if (w.bit_length() < r2 + 0) w.skip(r2 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.crc), 16, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Batch_ConvertToWire(const Batch& msg, uint8_t (&wire)[Batch::kMaxBytes]) {
    return Batch_ConvertToWire(msg, wire, Batch::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Batch_ConvertToHost(const uint8_t* wire, size_t len, Batch& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // count
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.count = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    r.align_to(8);

    // --- region 1 (Variable) ---
    const size_t r1 = r.bit_offset();
    // payload
    if (r.bit_offset() < r1 + 0) r.skip(r1 + 0 - r.bit_offset());
    for (size_t i = 0; i < static_cast<size_t>(msg.count) && i < 32; ++i) {
        msg.payload[i] = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    }

    // --- region 2 (Fixed) ---
    const size_t r2 = r.bit_offset();
    // crc
    if (r.bit_offset() < r2 + 0) r.skip(r2 + 0 - r.bit_offset());
    msg.crc = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Little));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

} // namespace proto

#endif // PROTODESIGNER_BULK_H
