// -----------------------------------------------------------------------------
// DynamicSample — shared type declarations
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
//
// Types are project-wide, so a struct used by two buses is one struct. It is declared
// here so that several bus headers can be included in the same translation unit.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_PROTO_TYPES_H
#define PROTODESIGNER_PROTO_TYPES_H

#include "protodesigner_runtime.h"

namespace proto {

} // namespace proto

#endif // PROTODESIGNER_PROTO_TYPES_H
