/* -----------------------------------------------------------------------------
   PrefixedSample - shared type declarations
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.

   Types are project-wide, so a struct used by two buses is one struct. It is declared
   here so that several bus headers can be included in the same translation unit.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_PROTO_TYPES_H
#define PROTODESIGNER_PROTO_TYPES_H

#include "protodesigner_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Wire sizes of the named primitives. There is no type to declare - the host
   kind is a built-in - but the width each one occupies is worth stating. */
#define PROTO_U8_ON_WIRE_BITS 8
#define PROTO_U8_ON_WIRE_BYTES 1
#define PROTO_U16_ON_WIRE_BITS 16
#define PROTO_U16_ON_WIRE_BYTES 2

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_PROTO_TYPES_H */
