/* -----------------------------------------------------------------------------
   PrefixedSample - bus 'Framed' (Ethernet)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_FRAMED_H
#define PROTODESIGNER_FRAMED_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Framed' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_FramedMessageId {
    proto_FramedMessageId_NotAssigned = 0,
    proto_FramedMessageId_Frame = 31,
} proto_FramedMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_FramedMessageId proto_Framed_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 31u: return proto_FramedMessageId_Frame;
        default: break;
    }
    return proto_FramedMessageId_NotAssigned;
}

/* Message 'Frame' (wire id 31) - 32..224 bits / 4..28 bytes. */
#define PROTO_FRAME_WIRE_ID 31u
#define PROTO_FRAME_MAX_BYTES 28

typedef struct proto_Frame {
    uint8_t kind;
    /* 'payload': up to 24, 8-bit length prefix */
    uint8_t payload[24];
    uint32_t payload_count;
    uint16_t trailer;
} proto_Frame;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Frame_OnWireLength(const proto_Frame* msg) {
    size_t bits = 0;
    bits += 16;                 /* region 0 (Fixed) */
    bits = ((bits + 7) / 8) * 8;   /* the encoder pads each fixed region to a byte */
    {   /* region 1 (Variable), up to 24 x 8 bits */
        size_t n = (size_t)(msg->payload_count);
        if (n > 24) n = 24;   /* the encoder truncates at capacity */
        bits += 8;                /* inline length prefix */
        bits += n * 8;
    }
    bits += 16;                 /* region 2 (Fixed) */
    bits = ((bits + 7) / 8) * 8;   /* the encoder pads each fixed region to a byte */
    return (bits + 7) / 8;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_FRAME_MAX_BYTES]. */
PD_INLINE size_t proto_Frame_ConvertToWire(const proto_Frame* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* kind */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->kind), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    /* --- region 1 (Variable) --- */
    { const size_t r1 = pd_bw_bit_length(&w);
    /* payload */
    if (pd_bw_bit_length(&w) < r1 + 0) pd_bw_skip(&w, r1 + 0 - pd_bw_bit_length(&w));
    { uint64_t n = (uint64_t)(msg->payload_count); if (n > 24u) n = 24u;
      pd_bw_write_unsigned(&w, n, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST); }
    for (size_t i = 0; i < (size_t)(msg->payload_count) && i < 24; ++i) {
        pd_bw_write_unsigned(&w, (uint64_t)(msg->payload[i]), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    }
    }

    /* --- region 2 (Fixed) --- */
    { const size_t r2 = pd_bw_bit_length(&w);
    /* trailer */
    if (pd_bw_bit_length(&w) < r2 + 0) pd_bw_skip(&w, r2 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->trailer), 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Frame_ConvertToHost(const uint8_t* wire, size_t len, proto_Frame* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* kind */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->kind = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    /* --- region 1 (Variable) --- */
    { const size_t r1 = pd_br_bit_offset(&r);
    /* payload */
    if (pd_br_bit_offset(&r) < r1 + 0) pd_br_skip(&r, r1 + 0 - pd_br_bit_offset(&r));
    msg->payload_count = (uint32_t)pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    for (size_t i = 0; i < (size_t)(msg->payload_count) && i < 24; ++i) {
        msg->payload[i] = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    }
    }

    /* --- region 2 (Fixed) --- */
    { const size_t r2 = pd_br_bit_offset(&r);
    /* trailer */
    if (pd_br_bit_offset(&r) < r2 + 0) pd_br_skip(&r, r2 + 0 - pd_br_bit_offset(&r));
    msg->trailer = (uint16_t)(pd_br_read_unsigned(&r, 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_FRAMED_H */
