// -----------------------------------------------------------------------------
// PackedSample — shared type declarations
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
//
// Types are project-wide, so a struct used by two buses is one struct. It is declared
// here so that several bus headers can be included in the same translation unit.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_PROTO_TYPES_H
#define PROTODESIGNER_PROTO_TYPES_H

#include "protodesigner_runtime.h"

namespace proto {

// Enumeration 'Mode'.
enum class Mode : uint32_t {
    Idle = 0,
    Arming = 1,
    Running = 5,
    Fault = 10,
};

} // namespace proto

#endif // PROTODESIGNER_PROTO_TYPES_H
