/* -----------------------------------------------------------------------------
   PackedSample - bus 'Control' (Uart)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_CONTROL_H
#define PROTODESIGNER_CONTROL_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Control' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_ControlMessageId {
    proto_ControlMessageId_NotAssigned = 0,
    proto_ControlMessageId_Status = 9,
} proto_ControlMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_ControlMessageId proto_Control_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 9u: return proto_ControlMessageId_Status;
        default: break;
    }
    return proto_ControlMessageId_NotAssigned;
}

/* Message 'Status' (wire id 9) - fixed 24 bits / 3 bytes. */
#define PROTO_STATUS_WIRE_ID 9u
#define PROTO_STATUS_MAX_BYTES 3

typedef struct proto_Status {
    proto_Mode mode;
    uint16_t temperature;   /* 4 bits */
    uint16_t checksum;
} proto_Status;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Status_OnWireLength(const proto_Status* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_STATUS_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_STATUS_MAX_BYTES]. */
PD_INLINE size_t proto_Status_ConvertToWire(const proto_Status* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* mode */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)((int64_t)(msg->mode)), 4, PD_ENDIAN_LITTLE);
    /* temperature */
    if (pd_bw_bit_length(&w) < r0 + 4) pd_bw_skip(&w, r0 + 4 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(((msg->temperature) - 1000)), 4, PD_ENDIAN_LITTLE);
    /* checksum */
    if (pd_bw_bit_length(&w) < r0 + 8) pd_bw_skip(&w, r0 + 8 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->checksum), 16, PD_ENDIAN_LITTLE);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Status_ConvertToHost(const uint8_t* wire, size_t len, proto_Status* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* mode */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->mode = (proto_Mode)(pd_br_read_unsigned(&r, 4, PD_ENDIAN_LITTLE));
    /* temperature */
    if (pd_br_bit_offset(&r) < r0 + 4) pd_br_skip(&r, r0 + 4 - pd_br_bit_offset(&r));
    msg->temperature = (uint16_t)(((pd_br_read_unsigned(&r, 4, PD_ENDIAN_LITTLE)) + 1000));
    /* checksum */
    if (pd_br_bit_offset(&r) < r0 + 8) pd_br_skip(&r, r0 + 8 - pd_br_bit_offset(&r));
    msg->checksum = (uint16_t)(pd_br_read_unsigned(&r, 16, PD_ENDIAN_LITTLE));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_CONTROL_H */
