// -----------------------------------------------------------------------------
// PackedSample — bus 'Control' (Uart)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_CONTROL_H
#define PROTODESIGNER_CONTROL_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Control' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class ControlMessageId : uint32_t {
    NotAssigned = 0,
    Status = 9u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline ControlMessageId Control_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 9u: return ControlMessageId::Status;
        default: break;
    }
    return ControlMessageId::NotAssigned;
}

// Message 'Status' (wire id 9) — fixed 24 bits / 3 bytes.
struct Status {
    static constexpr uint32_t kWireId = 9u;
    static constexpr size_t kMaxBytes = 3;

    Mode mode;
    uint16_t temperature;   // 4 bits
    uint16_t checksum;
};

// The number of bytes this message occupies on the wire.
// Fixed-size message, so the answer does not depend on the contents.
inline size_t Status_OnWireLength(const Status& msg) {
    (void)msg;
    return Status::kMaxBytes;
}

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Status_ConvertToWire(const Status& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // mode
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(static_cast<int64_t>(msg.mode)), 4, protodesigner::Endian::Little);
    // temperature
    if (w.bit_length() < r0 + 4) w.skip(r0 + 4 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(((msg.temperature) - 1000)), 4, protodesigner::Endian::Little);
    // checksum
    if (w.bit_length() < r0 + 8) w.skip(r0 + 8 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.checksum), 16, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Status_ConvertToWire(const Status& msg, uint8_t (&wire)[Status::kMaxBytes]) {
    return Status_ConvertToWire(msg, wire, Status::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Status_ConvertToHost(const uint8_t* wire, size_t len, Status& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // mode
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.mode = static_cast<Mode>(r.read_unsigned(4, protodesigner::Endian::Little));
    // temperature
    if (r.bit_offset() < r0 + 4) r.skip(r0 + 4 - r.bit_offset());
    msg.temperature = static_cast<uint16_t>(((r.read_unsigned(4, protodesigner::Endian::Little)) + 1000));
    // checksum
    if (r.bit_offset() < r0 + 8) r.skip(r0 + 8 - r.bit_offset());
    msg.checksum = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Little));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Status_ConvertToHost(const uint8_t (&wire)[Status::kMaxBytes], Status& msg) {
    return Status_ConvertToHost(wire, Status::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_CONTROL_H
