/* -----------------------------------------------------------------------------
   PackedSample - shared type declarations
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.

   Types are project-wide, so a struct used by two buses is one struct. It is declared
   here so that several bus headers can be included in the same translation unit.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_PROTO_TYPES_H
#define PROTODESIGNER_PROTO_TYPES_H

#include "protodesigner_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Wire sizes of the named primitives. There is no type to declare - the host
   kind is a built-in - but the width each one occupies is worth stating. */
#define PROTO_TEMPERATURE_ON_WIRE_BITS 16
#define PROTO_TEMPERATURE_ON_WIRE_BYTES 2
#define PROTO_U16_ON_WIRE_BITS 16
#define PROTO_U16_ON_WIRE_BYTES 2

/* Enumeration 'Mode'. */
typedef enum proto_Mode {
    proto_Mode_Idle = 0,
    proto_Mode_Arming = 1,
    proto_Mode_Running = 5,
    proto_Mode_Fault = 10,
} proto_Mode;
/* Wire size of Mode itself. An individual field may narrow it - check the
   field's own width in the message below before assuming this one applies to it. */
#define PROTO_MODE_ON_WIRE_BITS 32
#define PROTO_MODE_ON_WIRE_BYTES 4

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_PROTO_TYPES_H */
