/* -----------------------------------------------------------------------------
   QuantizedSample - bus 'Sensors' (Uart)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_SENSORS_H
#define PROTODESIGNER_SENSORS_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Sensors' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_SensorsMessageId {
    proto_SensorsMessageId_NotAssigned = 0,
    proto_SensorsMessageId_Ambient = 5,
} proto_SensorsMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_SensorsMessageId proto_Sensors_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 5u: return proto_SensorsMessageId_Ambient;
        default: break;
    }
    return proto_SensorsMessageId_NotAssigned;
}

/* Message 'Ambient' (wire id 5) - fixed 16 bits / 2 bytes. */
#define PROTO_AMBIENT_WIRE_ID 5u
#define PROTO_AMBIENT_MAX_BYTES 2

typedef struct proto_Ambient {
    double temperature;   /* 8 bits */
    float battery;   /* 8 bits */
} proto_Ambient;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Ambient_OnWireLength(const proto_Ambient* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_AMBIENT_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_AMBIENT_MAX_BYTES]. */
PD_INLINE size_t proto_Ambient_ConvertToWire(const proto_Ambient* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* temperature */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(pd_quantize(((((msg->temperature) + 40)) / 0.43137254901960786))), 8, PD_ENDIAN_LITTLE);
    /* battery */
    if (pd_bw_bit_length(&w) < r0 + 8) pd_bw_skip(&w, r0 + 8 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(pd_quantize(((msg->battery) / 0.3921568627450981))), 8, PD_ENDIAN_LITTLE);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Ambient_ConvertToHost(const uint8_t* wire, size_t len, proto_Ambient* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* temperature */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->temperature = (double)(((((pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE)) * 0.43137254901960786)) - 40));
    /* battery */
    if (pd_br_bit_offset(&r) < r0 + 8) pd_br_skip(&r, r0 + 8 - pd_br_bit_offset(&r));
    msg->battery = (float)(((pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE)) * 0.3921568627450981));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_SENSORS_H */
