// -----------------------------------------------------------------------------
// QuantizedSample — bus 'Sensors' (Uart)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_SENSORS_H
#define PROTODESIGNER_SENSORS_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Sensors' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class SensorsMessageId : uint32_t {
    NotAssigned = 0,
    Ambient = 5u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline SensorsMessageId Sensors_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 5u: return SensorsMessageId::Ambient;
        default: break;
    }
    return SensorsMessageId::NotAssigned;
}

// Message 'Ambient' (wire id 5) — fixed 16 bits / 2 bytes.
struct Ambient {
    static constexpr uint32_t kWireId = 5u;
    static constexpr size_t kMinBits  = 16;
    static constexpr size_t kMaxBits  = 16;
    static constexpr size_t kMaxBytes = 2;

    double temperature;   // 8 bits
    float battery;   // 8 bits
};

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Ambient_ConvertToWire(const Ambient& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // temperature
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(protodesigner::quantize(((((msg.temperature) + 40)) / 0.43137254901960786))), 8, protodesigner::Endian::Little);
    // battery
    if (w.bit_length() < r0 + 8) w.skip(r0 + 8 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(protodesigner::quantize(((msg.battery) / 0.3921568627450981))), 8, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Ambient_ConvertToWire(const Ambient& msg, uint8_t (&wire)[Ambient::kMaxBytes]) {
    return Ambient_ConvertToWire(msg, wire, Ambient::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Ambient_ConvertToHost(const uint8_t* wire, size_t len, Ambient& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // temperature
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.temperature = static_cast<double>(((((r.read_unsigned(8, protodesigner::Endian::Little)) * 0.43137254901960786)) - 40));
    // battery
    if (r.bit_offset() < r0 + 8) r.skip(r0 + 8 - r.bit_offset());
    msg.battery = static_cast<float>(((r.read_unsigned(8, protodesigner::Endian::Little)) * 0.3921568627450981));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Ambient_ConvertToHost(const uint8_t (&wire)[Ambient::kMaxBytes], Ambient& msg) {
    return Ambient_ConvertToHost(wire, Ambient::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_SENSORS_H
