// -----------------------------------------------------------------------------
// RawFloatSample — bus 'Analog' (Ethernet)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_ANALOG_H
#define PROTODESIGNER_ANALOG_H

#include "protodesigner_runtime.h"

namespace proto {

// Message 'Raw' (wire id 2) — fixed 64 bits / 8 bytes.
struct Raw {
    static constexpr uint32_t kWireId = 2u;
    static constexpr size_t kMinBits  = 64;
    static constexpr size_t kMaxBits  = 64;
    static constexpr size_t kMaxBytes = 8;

    double reading;   // 64 bits, raw IEEE-754
};

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t ConvertToWire(const Raw& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // reading
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(protodesigner::double_bits(msg.reading)), 64, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t ConvertToWire(const Raw& msg, uint8_t (&wire)[Raw::kMaxBytes]) {
    return ConvertToWire(msg, wire, Raw::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult ConvertToHost(const uint8_t* wire, size_t len, Raw& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // reading
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.reading = protodesigner::bits_to_double(static_cast<uint64_t>(r.read_unsigned(64, protodesigner::Endian::Little)));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult ConvertToHost(const uint8_t (&wire)[Raw::kMaxBytes], Raw& msg) {
    return ConvertToHost(wire, Raw::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_ANALOG_H
