/* -----------------------------------------------------------------------------
   RawFloatSample - bus 'Analog' (Ethernet)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_ANALOG_H
#define PROTODESIGNER_ANALOG_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Analog' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_AnalogMessageId {
    proto_AnalogMessageId_NotAssigned = 0,
    proto_AnalogMessageId_Raw = 2,
} proto_AnalogMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_AnalogMessageId proto_Analog_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 2u: return proto_AnalogMessageId_Raw;
        default: break;
    }
    return proto_AnalogMessageId_NotAssigned;
}

/* Message 'Raw' (wire id 2) - fixed 64 bits / 8 bytes. */
#define PROTO_RAW_WIRE_ID 2u
#define PROTO_RAW_MAX_BYTES 8

typedef struct proto_Raw {
    double reading;   /* 64 bits */
} proto_Raw;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Raw_OnWireLength(const proto_Raw* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_RAW_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_RAW_MAX_BYTES]. */
PD_INLINE size_t proto_Raw_ConvertToWire(const proto_Raw* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* reading */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(pd_double_bits(msg->reading)), 64, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Raw_ConvertToHost(const uint8_t* wire, size_t len, proto_Raw* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* reading */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->reading = pd_bits_to_double((uint64_t)pd_br_read_unsigned(&r, 64, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_ANALOG_H */
