// -----------------------------------------------------------------------------
// ScalarSample — bus 'Main' (Ethernet)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_MAIN_H
#define PROTODESIGNER_MAIN_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Main' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class MainMessageId : uint32_t {
    NotAssigned = 0,
    Reading = 3u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline MainMessageId Main_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 3u: return MainMessageId::Reading;
        default: break;
    }
    return MainMessageId::NotAssigned;
}

// Message 'Reading' (wire id 3) — fixed 56 bits / 7 bytes.
struct Reading {
    static constexpr uint32_t kWireId = 3u;
    static constexpr size_t kMaxBytes = 7;

    uint8_t id;
    uint16_t sequence;
    int32_t delta;
};

// The number of bytes this message occupies on the wire.
// Fixed-size message, so the answer does not depend on the contents.
inline size_t Reading_OnWireLength(const Reading& msg) {
    (void)msg;
    return Reading::kMaxBytes;
}

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Reading_ConvertToWire(const Reading& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // id
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.id), 8, protodesigner::Endian::Little);
    // sequence
    if (w.bit_length() < r0 + 8) w.skip(r0 + 8 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.sequence), 16, protodesigner::Endian::Big);
    // delta
    if (w.bit_length() < r0 + 24) w.skip(r0 + 24 - w.bit_length());
    w.write_signed(static_cast<int64_t>(msg.delta), 32, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Reading_ConvertToWire(const Reading& msg, uint8_t (&wire)[Reading::kMaxBytes]) {
    return Reading_ConvertToWire(msg, wire, Reading::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Reading_ConvertToHost(const uint8_t* wire, size_t len, Reading& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // id
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.id = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    // sequence
    if (r.bit_offset() < r0 + 8) r.skip(r0 + 8 - r.bit_offset());
    msg.sequence = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Big));
    // delta
    if (r.bit_offset() < r0 + 24) r.skip(r0 + 24 - r.bit_offset());
    msg.delta = static_cast<int32_t>(r.read_signed(32, protodesigner::Endian::Little));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Reading_ConvertToHost(const uint8_t (&wire)[Reading::kMaxBytes], Reading& msg) {
    return Reading_ConvertToHost(wire, Reading::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_MAIN_H
