/* -----------------------------------------------------------------------------
   ScalarSample - bus 'Main' (Ethernet)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_MAIN_H
#define PROTODESIGNER_MAIN_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Main' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_MainMessageId {
    proto_MainMessageId_NotAssigned = 0,
    proto_MainMessageId_Reading = 3,
} proto_MainMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_MainMessageId proto_Main_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 3u: return proto_MainMessageId_Reading;
        default: break;
    }
    return proto_MainMessageId_NotAssigned;
}

/* Message 'Reading' (wire id 3) - fixed 56 bits / 7 bytes. */
#define PROTO_READING_WIRE_ID 3u
#define PROTO_READING_MAX_BYTES 7

typedef struct proto_Reading {
    uint8_t id;
    uint16_t sequence;
    int32_t delta;
} proto_Reading;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Reading_OnWireLength(const proto_Reading* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_READING_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_READING_MAX_BYTES]. */
PD_INLINE size_t proto_Reading_ConvertToWire(const proto_Reading* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* id */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->id), 8, PD_ENDIAN_LITTLE);
    /* sequence */
    if (pd_bw_bit_length(&w) < r0 + 8) pd_bw_skip(&w, r0 + 8 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->sequence), 16, PD_ENDIAN_BIG);
    /* delta */
    if (pd_bw_bit_length(&w) < r0 + 24) pd_bw_skip(&w, r0 + 24 - pd_bw_bit_length(&w));
    pd_bw_write_signed(&w, (int64_t)(msg->delta), 32, PD_ENDIAN_LITTLE);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Reading_ConvertToHost(const uint8_t* wire, size_t len, proto_Reading* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* id */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->id = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE));
    /* sequence */
    if (pd_br_bit_offset(&r) < r0 + 8) pd_br_skip(&r, r0 + 8 - pd_br_bit_offset(&r));
    msg->sequence = (uint16_t)(pd_br_read_unsigned(&r, 16, PD_ENDIAN_BIG));
    /* delta */
    if (pd_br_bit_offset(&r) < r0 + 24) pd_br_skip(&r, r0 + 24 - pd_br_bit_offset(&r));
    msg->delta = (int32_t)(pd_br_read_signed(&r, 32, PD_ENDIAN_LITTLE));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_MAIN_H */
