/* -----------------------------------------------------------------------------
   SharedStructSample - bus 'Shared' (Ethernet)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_SHARED_H
#define PROTODESIGNER_SHARED_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Shared' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_SharedMessageId {
    proto_SharedMessageId_NotAssigned = 0,
    proto_SharedMessageId_Alpha = 1,
    proto_SharedMessageId_Beta = 2,
} proto_SharedMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_SharedMessageId proto_Shared_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 1u: return proto_SharedMessageId_Alpha;
        case 2u: return proto_SharedMessageId_Beta;
        default: break;
    }
    return proto_SharedMessageId_NotAssigned;
}

/* Message 'Alpha' (wire id 1) - fixed 56 bits / 7 bytes. */
#define PROTO_ALPHA_WIRE_ID 1u
#define PROTO_ALPHA_MAX_BYTES 7

typedef struct proto_Alpha {
    proto_Header header;
    uint16_t value;
} proto_Alpha;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Alpha_OnWireLength(const proto_Alpha* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_ALPHA_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_ALPHA_MAX_BYTES]. */
PD_INLINE size_t proto_Alpha_ConvertToWire(const proto_Alpha* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* header.messageId */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->header.messageId), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* header.timestamp */
    if (pd_bw_bit_length(&w) < r0 + 8) pd_bw_skip(&w, r0 + 8 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->header.timestamp), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* value */
    if (pd_bw_bit_length(&w) < r0 + 40) pd_bw_skip(&w, r0 + 40 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->value), 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Alpha_ConvertToHost(const uint8_t* wire, size_t len, proto_Alpha* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* header.messageId */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->header.messageId = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* header.timestamp */
    if (pd_br_bit_offset(&r) < r0 + 8) pd_br_skip(&r, r0 + 8 - pd_br_bit_offset(&r));
    msg->header.timestamp = (uint32_t)(pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* value */
    if (pd_br_bit_offset(&r) < r0 + 40) pd_br_skip(&r, r0 + 40 - pd_br_bit_offset(&r));
    msg->value = (uint16_t)(pd_br_read_unsigned(&r, 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

/* Message 'Beta' (wire id 2) - fixed 96 bits / 12 bytes. */
#define PROTO_BETA_WIRE_ID 2u
#define PROTO_BETA_MAX_BYTES 12

typedef struct proto_Beta {
    proto_Header header;
    proto_Envelope envelope;
} proto_Beta;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Beta_OnWireLength(const proto_Beta* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_BETA_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_BETA_MAX_BYTES]. */
PD_INLINE size_t proto_Beta_ConvertToWire(const proto_Beta* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* header.messageId */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->header.messageId), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* header.timestamp */
    if (pd_bw_bit_length(&w) < r0 + 8) pd_bw_skip(&w, r0 + 8 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->header.timestamp), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* envelope.head.messageId */
    if (pd_bw_bit_length(&w) < r0 + 40) pd_bw_skip(&w, r0 + 40 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->envelope.head.messageId), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* envelope.head.timestamp */
    if (pd_bw_bit_length(&w) < r0 + 48) pd_bw_skip(&w, r0 + 48 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->envelope.head.timestamp), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* envelope.sequence */
    if (pd_bw_bit_length(&w) < r0 + 80) pd_bw_skip(&w, r0 + 80 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->envelope.sequence), 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Beta_ConvertToHost(const uint8_t* wire, size_t len, proto_Beta* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* header.messageId */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->header.messageId = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* header.timestamp */
    if (pd_br_bit_offset(&r) < r0 + 8) pd_br_skip(&r, r0 + 8 - pd_br_bit_offset(&r));
    msg->header.timestamp = (uint32_t)(pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* envelope.head.messageId */
    if (pd_br_bit_offset(&r) < r0 + 40) pd_br_skip(&r, r0 + 40 - pd_br_bit_offset(&r));
    msg->envelope.head.messageId = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* envelope.head.timestamp */
    if (pd_br_bit_offset(&r) < r0 + 48) pd_br_skip(&r, r0 + 48 - pd_br_bit_offset(&r));
    msg->envelope.head.timestamp = (uint32_t)(pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* envelope.sequence */
    if (pd_br_bit_offset(&r) < r0 + 80) pd_br_skip(&r, r0 + 80 - pd_br_bit_offset(&r));
    msg->envelope.sequence = (uint16_t)(pd_br_read_unsigned(&r, 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_SHARED_H */
