/* -----------------------------------------------------------------------------
   SharedStructSample - shared type declarations
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.

   Types are project-wide, so a struct used by two buses is one struct. It is declared
   here so that several bus headers can be included in the same translation unit.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_PROTO_TYPES_H
#define PROTODESIGNER_PROTO_TYPES_H

#include "protodesigner_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Wire sizes of the named primitives. There is no type to declare - the host
   kind is a built-in - but the width each one occupies is worth stating. */
#define PROTO_U8_ON_WIRE_BITS 8
#define PROTO_U8_ON_WIRE_BYTES 1
#define PROTO_U32_ON_WIRE_BITS 32
#define PROTO_U32_ON_WIRE_BYTES 4
#define PROTO_U16_ON_WIRE_BITS 16
#define PROTO_U16_ON_WIRE_BYTES 2

/* Struct 'Header'. */
typedef struct proto_Header {
    uint8_t messageId;
    uint32_t timestamp;
} proto_Header;
/* Wire size of Header itself. An individual field may narrow it - check the
   field's own width in the message below before assuming this one applies to it. */
#define PROTO_HEADER_ON_WIRE_BITS 40
#define PROTO_HEADER_ON_WIRE_BYTES 5

/* Struct 'Envelope'. */
typedef struct proto_Envelope {
    proto_Header head;
    uint16_t sequence;
} proto_Envelope;
/* Wire size of Envelope itself. An individual field may narrow it - check the
   field's own width in the message below before assuming this one applies to it. */
#define PROTO_ENVELOPE_ON_WIRE_BITS 56
#define PROTO_ENVELOPE_ON_WIRE_BYTES 7

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_PROTO_TYPES_H */
