// -----------------------------------------------------------------------------
// SharedStructSample — bus 'Shared' (Ethernet)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_SHARED_H
#define PROTODESIGNER_SHARED_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Shared' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class SharedMessageId : uint32_t {
    NotAssigned = 0,
    Alpha = 1u,
    Beta = 2u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline SharedMessageId Shared_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 1u: return SharedMessageId::Alpha;
        case 2u: return SharedMessageId::Beta;
        default: break;
    }
    return SharedMessageId::NotAssigned;
}

// Message 'Alpha' (wire id 1) — fixed 56 bits / 7 bytes.
struct Alpha {
    static constexpr uint32_t kWireId = 1u;
    static constexpr size_t kMaxBytes = 7;

    Header header;
    uint16_t value;
};

// The number of bytes this message occupies on the wire.
// Fixed-size message, so the answer does not depend on the contents.
inline size_t Alpha_OnWireLength(const Alpha& msg) {
    (void)msg;
    return Alpha::kMaxBytes;
}

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Alpha_ConvertToWire(const Alpha& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // header.messageId
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.header.messageId), 8, protodesigner::Endian::Little);
    // header.timestamp
    if (w.bit_length() < r0 + 8) w.skip(r0 + 8 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.header.timestamp), 32, protodesigner::Endian::Little);
    // value
    if (w.bit_length() < r0 + 40) w.skip(r0 + 40 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.value), 16, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Alpha_ConvertToWire(const Alpha& msg, uint8_t (&wire)[Alpha::kMaxBytes]) {
    return Alpha_ConvertToWire(msg, wire, Alpha::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Alpha_ConvertToHost(const uint8_t* wire, size_t len, Alpha& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // header.messageId
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.header.messageId = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    // header.timestamp
    if (r.bit_offset() < r0 + 8) r.skip(r0 + 8 - r.bit_offset());
    msg.header.timestamp = static_cast<uint32_t>(r.read_unsigned(32, protodesigner::Endian::Little));
    // value
    if (r.bit_offset() < r0 + 40) r.skip(r0 + 40 - r.bit_offset());
    msg.value = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Little));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Alpha_ConvertToHost(const uint8_t (&wire)[Alpha::kMaxBytes], Alpha& msg) {
    return Alpha_ConvertToHost(wire, Alpha::kMaxBytes, msg);
}

// Message 'Beta' (wire id 2) — fixed 96 bits / 12 bytes.
struct Beta {
    static constexpr uint32_t kWireId = 2u;
    static constexpr size_t kMaxBytes = 12;

    Header header;
    Envelope envelope;
};

// The number of bytes this message occupies on the wire.
// Fixed-size message, so the answer does not depend on the contents.
inline size_t Beta_OnWireLength(const Beta& msg) {
    (void)msg;
    return Beta::kMaxBytes;
}

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Beta_ConvertToWire(const Beta& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // header.messageId
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.header.messageId), 8, protodesigner::Endian::Little);
    // header.timestamp
    if (w.bit_length() < r0 + 8) w.skip(r0 + 8 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.header.timestamp), 32, protodesigner::Endian::Little);
    // envelope.head.messageId
    if (w.bit_length() < r0 + 40) w.skip(r0 + 40 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.envelope.head.messageId), 8, protodesigner::Endian::Little);
    // envelope.head.timestamp
    if (w.bit_length() < r0 + 48) w.skip(r0 + 48 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.envelope.head.timestamp), 32, protodesigner::Endian::Little);
    // envelope.sequence
    if (w.bit_length() < r0 + 80) w.skip(r0 + 80 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.envelope.sequence), 16, protodesigner::Endian::Little);
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Beta_ConvertToWire(const Beta& msg, uint8_t (&wire)[Beta::kMaxBytes]) {
    return Beta_ConvertToWire(msg, wire, Beta::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Beta_ConvertToHost(const uint8_t* wire, size_t len, Beta& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // header.messageId
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.header.messageId = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    // header.timestamp
    if (r.bit_offset() < r0 + 8) r.skip(r0 + 8 - r.bit_offset());
    msg.header.timestamp = static_cast<uint32_t>(r.read_unsigned(32, protodesigner::Endian::Little));
    // envelope.head.messageId
    if (r.bit_offset() < r0 + 40) r.skip(r0 + 40 - r.bit_offset());
    msg.envelope.head.messageId = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    // envelope.head.timestamp
    if (r.bit_offset() < r0 + 48) r.skip(r0 + 48 - r.bit_offset());
    msg.envelope.head.timestamp = static_cast<uint32_t>(r.read_unsigned(32, protodesigner::Endian::Little));
    // envelope.sequence
    if (r.bit_offset() < r0 + 80) r.skip(r0 + 80 - r.bit_offset());
    msg.envelope.sequence = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Little));
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Beta_ConvertToHost(const uint8_t (&wire)[Beta::kMaxBytes], Beta& msg) {
    return Beta_ConvertToHost(wire, Beta::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_SHARED_H
