/* -----------------------------------------------------------------------------
   CompositeSample - bus 'Telemetry' (Ethernet)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_TELEMETRY_H
#define PROTODESIGNER_TELEMETRY_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Telemetry' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_TelemetryMessageId {
    proto_TelemetryMessageId_NotAssigned = 0,
    proto_TelemetryMessageId_Frame = 12,
} proto_TelemetryMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_TelemetryMessageId proto_Telemetry_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 12u: return proto_TelemetryMessageId_Frame;
        default: break;
    }
    return proto_TelemetryMessageId_NotAssigned;
}

/* Message 'Frame' (wire id 12) - fixed 104 bits / 13 bytes. */
#define PROTO_FRAME_WIRE_ID 12u
#define PROTO_FRAME_MAX_BYTES 13

typedef struct proto_Frame {
    proto_Header header;
    /* 'samples': exactly 4 elements */
    uint16_t samples[4];
} proto_Frame;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Frame_OnWireLength(const proto_Frame* msg) {
    (void)msg;   /* fixed size: the contents do not matter */
    return PROTO_FRAME_MAX_BYTES;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_FRAME_MAX_BYTES]. */
PD_INLINE size_t proto_Frame_ConvertToWire(const proto_Frame* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* header.messageId */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->header.messageId), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* header.timestamp */
    if (pd_bw_bit_length(&w) < r0 + 8) pd_bw_skip(&w, r0 + 8 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->header.timestamp), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    /* samples */
    if (pd_bw_bit_length(&w) < r0 + 40) pd_bw_skip(&w, r0 + 40 - pd_bw_bit_length(&w));
    for (size_t i = 0; i < (size_t)(4) && i < 4; ++i) {
        pd_bw_write_unsigned(&w, (uint64_t)(msg->samples[i]), 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    }
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Frame_ConvertToHost(const uint8_t* wire, size_t len, proto_Frame* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* header.messageId */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->header.messageId = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* header.timestamp */
    if (pd_br_bit_offset(&r) < r0 + 8) pd_br_skip(&r, r0 + 8 - pd_br_bit_offset(&r));
    msg->header.timestamp = (uint32_t)(pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    /* samples */
    if (pd_br_bit_offset(&r) < r0 + 40) pd_br_skip(&r, r0 + 40 - pd_br_bit_offset(&r));
    for (size_t i = 0; i < (size_t)(4) && i < 4; ++i) {
        msg->samples[i] = (uint16_t)(pd_br_read_unsigned(&r, 16, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    }
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_TELEMETRY_H */
