/* -----------------------------------------------------------------------------
   StructArraySample - shared type declarations
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.

   Types are project-wide, so a struct used by two buses is one struct. It is declared
   here so that several bus headers can be included in the same translation unit.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_PROTO_TYPES_H
#define PROTODESIGNER_PROTO_TYPES_H

#include "protodesigner_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Wire sizes of the named primitives. There is no type to declare - the host
   kind is a built-in - but the width each one occupies is worth stating. */
#define PROTO_U8_ON_WIRE_BITS 8
#define PROTO_U8_ON_WIRE_BYTES 1
#define PROTO_U32_ON_WIRE_BITS 32
#define PROTO_U32_ON_WIRE_BYTES 4
#define PROTO_F32_ON_WIRE_BITS 32
#define PROTO_F32_ON_WIRE_BYTES 4

/* Struct 'Reading'. */
typedef struct proto_Reading {
    uint8_t channel;
    uint8_t value;
} proto_Reading;
/* Wire size of Reading itself. An individual field may narrow it - check the
   field's own width in the message below before assuming this one applies to it. */
#define PROTO_READING_ON_WIRE_BITS 16
#define PROTO_READING_ON_WIRE_BYTES 2

/* Struct 'ChannelBlock'. */
typedef struct proto_ChannelBlock {
    uint32_t channelId;
    float scale;
    /* 'samples': exactly 4 elements */
    uint8_t samples[4];
} proto_ChannelBlock;
/* Wire size of ChannelBlock itself. An individual field may narrow it - check the
   field's own width in the message below before assuming this one applies to it. */
#define PROTO_CHANNELBLOCK_ON_WIRE_BITS 96
#define PROTO_CHANNELBLOCK_ON_WIRE_BYTES 12

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_PROTO_TYPES_H */
