// -----------------------------------------------------------------------------
// CompositeSample — bus 'Telemetry' (Ethernet)
// Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
// -----------------------------------------------------------------------------
#ifndef PROTODESIGNER_TELEMETRY_H
#define PROTODESIGNER_TELEMETRY_H

#include "proto_types.h"

namespace proto {

// Every message on bus 'Telemetry' that carries an id. Ids are unique within a
// bus and start at 1, so 0 is free to mean "no such message".
enum class TelemetryMessageId : uint32_t {
    NotAssigned = 0,
    Frame = 12u,
};

// Maps a wire id onto the message it identifies, or NotAssigned if this bus has none.
inline TelemetryMessageId Telemetry_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 12u: return TelemetryMessageId::Frame;
        default: break;
    }
    return TelemetryMessageId::NotAssigned;
}

// Message 'Frame' (wire id 12) — fixed 104 bits / 13 bytes.
struct Frame {
    static constexpr uint32_t kWireId = 12u;
    static constexpr size_t kMinBits  = 104;
    static constexpr size_t kMaxBits  = 104;
    static constexpr size_t kMaxBytes = 13;

    Header header;
    // 'samples': exactly 4 elements
    uint16_t samples[4];
};

// Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
// Returns the number of bytes written, or 0 if the buffer was too small.
inline size_t Frame_ConvertToWire(const Frame& msg, uint8_t* wire, size_t cap) {
    protodesigner::BitWriter w(wire, cap);

    // --- region 0 (Fixed) ---
    const size_t r0 = w.bit_length();
    // header.messageId
    if (w.bit_length() < r0 + 0) w.skip(r0 + 0 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.header.messageId), 8, protodesigner::Endian::Little);
    // header.timestamp
    if (w.bit_length() < r0 + 8) w.skip(r0 + 8 - w.bit_length());
    w.write_unsigned(static_cast<uint64_t>(msg.header.timestamp), 32, protodesigner::Endian::Little);
    // samples
    if (w.bit_length() < r0 + 40) w.skip(r0 + 40 - w.bit_length());
    for (size_t i = 0; i < static_cast<size_t>(4) && i < 4; ++i) {
        w.write_unsigned(static_cast<uint64_t>(msg.samples[i]), 16, protodesigner::Endian::Little);
    }
    w.pad_to(8);

    if (w.overflowed()) return 0;
    return w.byte_length();
}

// Same conversion into a correctly sized array. The capacity is checked at compile time.
inline size_t Frame_ConvertToWire(const Frame& msg, uint8_t (&wire)[Frame::kMaxBytes]) {
    return Frame_ConvertToWire(msg, wire, Frame::kMaxBytes);
}

// Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
// Returns DecodeResult::Ok() on success, or Fail(bit) if the frame ran out early.
inline protodesigner::DecodeResult Frame_ConvertToHost(const uint8_t* wire, size_t len, Frame& msg) {
    protodesigner::BitReader r(wire, len);

    // --- region 0 (Fixed) ---
    const size_t r0 = r.bit_offset();
    // header.messageId
    if (r.bit_offset() < r0 + 0) r.skip(r0 + 0 - r.bit_offset());
    msg.header.messageId = static_cast<uint8_t>(r.read_unsigned(8, protodesigner::Endian::Little));
    // header.timestamp
    if (r.bit_offset() < r0 + 8) r.skip(r0 + 8 - r.bit_offset());
    msg.header.timestamp = static_cast<uint32_t>(r.read_unsigned(32, protodesigner::Endian::Little));
    // samples
    if (r.bit_offset() < r0 + 40) r.skip(r0 + 40 - r.bit_offset());
    for (size_t i = 0; i < static_cast<size_t>(4) && i < 4; ++i) {
        msg.samples[i] = static_cast<uint16_t>(r.read_unsigned(16, protodesigner::Endian::Little));
    }
    r.align_to(8);

    if (r.underflowed()) return protodesigner::DecodeResult::Fail(r.bit_offset());
    return protodesigner::DecodeResult::Ok();
}

// Same conversion from a full frame. Fixed-size message, so the length is implied.
inline protodesigner::DecodeResult Frame_ConvertToHost(const uint8_t (&wire)[Frame::kMaxBytes], Frame& msg) {
    return Frame_ConvertToHost(wire, Frame::kMaxBytes, msg);
}

} // namespace proto

#endif // PROTODESIGNER_TELEMETRY_H
