/* -----------------------------------------------------------------------------
   StructArraySample - bus 'Sensors' (Ethernet)
   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.
   ----------------------------------------------------------------------------- */
#ifndef PROTODESIGNER_SENSORS_H
#define PROTODESIGNER_SENSORS_H

#include "proto_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Every message on bus 'Sensors' that carries an id. Ids are unique within a
   bus and start at 1, so 0 is free to mean "no such message". */
typedef enum proto_SensorsMessageId {
    proto_SensorsMessageId_NotAssigned = 0,
    proto_SensorsMessageId_Bundle = 31,
} proto_SensorsMessageId;

/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */
PD_INLINE proto_SensorsMessageId proto_Sensors_MessageIdFromWire(uint32_t id) {
    switch (id) {
        case 31u: return proto_SensorsMessageId_Bundle;
        default: break;
    }
    return proto_SensorsMessageId_NotAssigned;
}

/* Message 'Bundle' (wire id 31) - 48..368 bits / 6..46 bytes. */
#define PROTO_BUNDLE_WIRE_ID 31u
#define PROTO_BUNDLE_MAX_BYTES 46

typedef struct proto_Bundle {
    uint8_t readingCount;
    /* 'readings': up to 8, count from an earlier field */
    proto_Reading readings[8];
    uint8_t blockCount;
    /* 'blocks': up to 2, count from an earlier field */
    proto_ChannelBlock blocks[2];
    uint32_t crc;
} proto_Bundle;

/* The number of bytes this message occupies on the wire. */
PD_INLINE size_t proto_Bundle_OnWireLength(const proto_Bundle* msg) {
    size_t bits = 0;
    bits += 8;                 /* region 0 (Fixed) */
    bits = ((bits + 7) / 8) * 8;   /* the encoder pads each fixed region to a byte */
    {   /* region 1 (Variable), up to 8 x 16 bits */
        size_t n = (size_t)(msg->readingCount);
        if (n > 8) n = 8;   /* the encoder truncates at capacity */
        bits += n * 16;
    }
    bits += 8;                 /* region 2 (Fixed) */
    bits = ((bits + 7) / 8) * 8;   /* the encoder pads each fixed region to a byte */
    {   /* region 3 (Variable), up to 2 x 96 bits */
        size_t n = (size_t)(msg->blockCount);
        if (n > 2) n = 2;   /* the encoder truncates at capacity */
        bits += n * 96;
    }
    bits += 32;                 /* region 4 (Fixed) */
    bits = ((bits + 7) / 8) * 8;   /* the encoder pads each fixed region to a byte */
    return (bits + 7) / 8;
}

/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).
   Returns the number of bytes written, or 0 if the buffer was too small.
   A correctly sized buffer is uint8_t wire[PROTO_BUNDLE_MAX_BYTES]. */
PD_INLINE size_t proto_Bundle_ConvertToWire(const proto_Bundle* msg, uint8_t* wire, size_t cap) {
    pd_bit_writer_t w;
    pd_bw_init(&w, wire, cap);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_bw_bit_length(&w);
    /* readingCount */
    if (pd_bw_bit_length(&w) < r0 + 0) pd_bw_skip(&w, r0 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->readingCount), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    /* --- region 1 (Variable) --- */
    { const size_t r1 = pd_bw_bit_length(&w);
    /* readings */
    if (pd_bw_bit_length(&w) < r1 + 0) pd_bw_skip(&w, r1 + 0 - pd_bw_bit_length(&w));
    for (size_t i = 0; i < (size_t)(msg->readingCount) && i < 8; ++i) {
        const size_t e = pd_bw_bit_length(&w);
        /* readings[].channel */
        if (pd_bw_bit_length(&w) < e + 0) pd_bw_skip(&w, e + 0 - pd_bw_bit_length(&w));
        pd_bw_write_unsigned(&w, (uint64_t)(msg->readings[i].channel), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
        /* readings[].value */
        if (pd_bw_bit_length(&w) < e + 8) pd_bw_skip(&w, e + 8 - pd_bw_bit_length(&w));
        pd_bw_write_unsigned(&w, (uint64_t)(msg->readings[i].value), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
        if (pd_bw_bit_length(&w) < e + 16) pd_bw_skip(&w, e + 16 - pd_bw_bit_length(&w));
    }
    }

    /* --- region 2 (Fixed) --- */
    { const size_t r2 = pd_bw_bit_length(&w);
    /* blockCount */
    if (pd_bw_bit_length(&w) < r2 + 0) pd_bw_skip(&w, r2 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->blockCount), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    /* --- region 3 (Variable) --- */
    { const size_t r3 = pd_bw_bit_length(&w);
    /* blocks */
    if (pd_bw_bit_length(&w) < r3 + 0) pd_bw_skip(&w, r3 + 0 - pd_bw_bit_length(&w));
    for (size_t i = 0; i < (size_t)(msg->blockCount) && i < 2; ++i) {
        const size_t e = pd_bw_bit_length(&w);
        /* blocks[].channelId */
        if (pd_bw_bit_length(&w) < e + 0) pd_bw_skip(&w, e + 0 - pd_bw_bit_length(&w));
        pd_bw_write_unsigned(&w, (uint64_t)(msg->blocks[i].channelId), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
        /* blocks[].scale */
        if (pd_bw_bit_length(&w) < e + 32) pd_bw_skip(&w, e + 32 - pd_bw_bit_length(&w));
        pd_bw_write_unsigned(&w, (uint64_t)(pd_float_bits(msg->blocks[i].scale)), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
        /* blocks[].samples */
        if (pd_bw_bit_length(&w) < e + 64) pd_bw_skip(&w, e + 64 - pd_bw_bit_length(&w));
        for (size_t j = 0; j < 4; ++j) {
            pd_bw_write_unsigned(&w, (uint64_t)(msg->blocks[i].samples[j]), 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
        }
        if (pd_bw_bit_length(&w) < e + 96) pd_bw_skip(&w, e + 96 - pd_bw_bit_length(&w));
    }
    }

    /* --- region 4 (Fixed) --- */
    { const size_t r4 = pd_bw_bit_length(&w);
    /* crc */
    if (pd_bw_bit_length(&w) < r4 + 0) pd_bw_skip(&w, r4 + 0 - pd_bw_bit_length(&w));
    pd_bw_write_unsigned(&w, (uint64_t)(msg->crc), 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST);
    pd_bw_pad_to(&w, 8);
    }

    if (pd_bw_overflowed(&w)) return 0;
    return pd_bw_byte_length(&w);
}

/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.
   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */
PD_INLINE pd_decode_result_t proto_Bundle_ConvertToHost(const uint8_t* wire, size_t len, proto_Bundle* msg) {
    pd_bit_reader_t r;
    pd_br_init(&r, wire, len);

    /* --- region 0 (Fixed) --- */
    { const size_t r0 = pd_br_bit_offset(&r);
    /* readingCount */
    if (pd_br_bit_offset(&r) < r0 + 0) pd_br_skip(&r, r0 + 0 - pd_br_bit_offset(&r));
    msg->readingCount = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    /* --- region 1 (Variable) --- */
    { const size_t r1 = pd_br_bit_offset(&r);
    /* readings */
    if (pd_br_bit_offset(&r) < r1 + 0) pd_br_skip(&r, r1 + 0 - pd_br_bit_offset(&r));
    for (size_t i = 0; i < (size_t)(msg->readingCount) && i < 8; ++i) {
        const size_t e = pd_br_bit_offset(&r);
        /* readings[].channel */
        if (pd_br_bit_offset(&r) < e + 0) pd_br_skip(&r, e + 0 - pd_br_bit_offset(&r));
        msg->readings[i].channel = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
        /* readings[].value */
        if (pd_br_bit_offset(&r) < e + 8) pd_br_skip(&r, e + 8 - pd_br_bit_offset(&r));
        msg->readings[i].value = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
        if (pd_br_bit_offset(&r) < e + 16) pd_br_skip(&r, e + 16 - pd_br_bit_offset(&r));
    }
    }

    /* --- region 2 (Fixed) --- */
    { const size_t r2 = pd_br_bit_offset(&r);
    /* blockCount */
    if (pd_br_bit_offset(&r) < r2 + 0) pd_br_skip(&r, r2 + 0 - pd_br_bit_offset(&r));
    msg->blockCount = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    /* --- region 3 (Variable) --- */
    { const size_t r3 = pd_br_bit_offset(&r);
    /* blocks */
    if (pd_br_bit_offset(&r) < r3 + 0) pd_br_skip(&r, r3 + 0 - pd_br_bit_offset(&r));
    for (size_t i = 0; i < (size_t)(msg->blockCount) && i < 2; ++i) {
        const size_t e = pd_br_bit_offset(&r);
        /* blocks[].channelId */
        if (pd_br_bit_offset(&r) < e + 0) pd_br_skip(&r, e + 0 - pd_br_bit_offset(&r));
        msg->blocks[i].channelId = (uint32_t)(pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
        /* blocks[].scale */
        if (pd_br_bit_offset(&r) < e + 32) pd_br_skip(&r, e + 32 - pd_br_bit_offset(&r));
        msg->blocks[i].scale = pd_bits_to_float((uint32_t)pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
        /* blocks[].samples */
        if (pd_br_bit_offset(&r) < e + 64) pd_br_skip(&r, e + 64 - pd_br_bit_offset(&r));
        for (size_t j = 0; j < 4; ++j) {
            msg->blocks[i].samples[j] = (uint8_t)(pd_br_read_unsigned(&r, 8, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
        }
        if (pd_br_bit_offset(&r) < e + 96) pd_br_skip(&r, e + 96 - pd_br_bit_offset(&r));
    }
    }

    /* --- region 4 (Fixed) --- */
    { const size_t r4 = pd_br_bit_offset(&r);
    /* crc */
    if (pd_br_bit_offset(&r) < r4 + 0) pd_br_skip(&r, r4 + 0 - pd_br_bit_offset(&r));
    msg->crc = (uint32_t)(pd_br_read_unsigned(&r, 32, PD_ENDIAN_LITTLE, PD_BITS_MSB_FIRST));
    pd_br_align_to(&r, 8);
    }

    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));
    return pd_decode_ok();
}

#ifdef __cplusplus
}   /* extern "C" */
#endif

#endif /* PROTODESIGNER_SENSORS_H */
