using System.Globalization;
using System.Text;
using ProtoDesigner.Core.Ir;
using ProtoDesigner.Core.Model;

namespace ProtoDesigner.CodeGen.C;

/// <summary>
/// Emits C conversion code for a protocol. Output is a fixed runtime header plus one header per bus
/// holding an enum per IR enum, a struct per shared struct type, a struct per message in its <em>host</em>
/// representation, a message-id enum for the bus, and the two conversions between each message and the
/// wire: <c>&lt;prefix&gt;_&lt;Message&gt;_ConvertToWire</c> and <c>_ConvertToHost</c>.
/// </summary>
/// <remarks>
/// <para>
/// C rather than C++, wrapped in <c>extern "C"</c> guards, so one generated header serves a C module and
/// a C++ module alike. A protocol definition should not decide what language the code that speaks it is
/// written in, and on the targets this aims at — microcontrollers — C is frequently the only option.
/// </para>
/// <para>
/// Two consequences worth knowing. C has no namespaces, so the namespace option becomes a symbol
/// <em>prefix</em>. And C has no overloading, so the fixed-size convenience variants that the C++ output
/// used to provide as overloads are gone rather than renamed: a second spelling of the same call earns
/// its keep only if it removes a mistake, and passing the wrong length is caught by the length argument
/// being required.
/// </para>
/// <para>
/// Offsets inside a <see cref="IrRegionKind.Fixed"/> region are emitted as compile-time constants.
/// A <see cref="IrRegionKind.Variable"/> region runs a cursor for its elements only; the fixed region
/// that follows it goes back to constant offsets relative to where the variable part ended.
/// </para>
/// </remarks>
public sealed class CGenerator : IProtocolGenerator
{
    public string Id => "c";

    public string DisplayName => "C99 (compiles as C or C++)";

    /// <summary>Option key: emit <c>extern "C"</c> guards so the header is usable from C++.</summary>
    public const string ExternCOption = "externc";

    public IReadOnlyList<GeneratorOption> Options { get; } = new[]
    {
        new GeneratorOption(
            ExternCOption,
            "extern \"C\" guards",
            "Wrap declarations so the header can be included from a C++ translation unit. Leave on "
            + "unless you know no C++ will ever see it.",
            GeneratorOptionKind.Flag,
            Default: "true"),
    };

    public GeneratedFileSet Generate(ProtocolIr ir, GeneratorOptions options)
    {
        ArgumentNullException.ThrowIfNull(ir);
        return Generate(new[] { ir }, options);
    }

    public GeneratedFileSet Generate(IReadOnlyList<ProtocolIr> buses, GeneratorOptions options)
    {
        ArgumentNullException.ThrowIfNull(buses);
        if (buses.Count == 0) return GeneratedFileSet.Empty;
        options ??= new GeneratorOptions();

        var files = new List<GeneratedFile>
        {
            new(CRuntimeHeader.FileName, CRuntimeHeader.Emit()),
            new(TypesFileName(options), EmitTypesHeader(buses, options)),
        };

        foreach (var ir in buses)
            files.Add(new($"{FileStem(ir.BusName)}.h", EmitProtocolHeader(ir, options)));

        if (options.IncludeReadme)
            files.Add(new("README.md", EmitReadme(buses, options)));

        return new GeneratedFileSet(files);
    }

    private static string Prefix(GeneratorOptions options) => CNaming.Prefix(options.Namespace);

    private static string FileStem(string busName) =>
        CNaming.TypeName("", busName).ToLowerInvariant();

    /// <summary>
    /// The shared declarations header. Enums and structs come from a project-wide library, so they are
    /// declared here once and included by every bus header rather than repeated in each — where two
    /// definitions of one struct would not compile at all.
    /// </summary>
    private static string TypesFileName(GeneratorOptions options) => $"{Prefix(options)}_types.h";

    private static string EmitTypesHeader(IReadOnlyList<ProtocolIr> buses, GeneratorOptions options)
    {
        var prefix = Prefix(options);
        var guard = $"PROTODESIGNER_{prefix.ToUpperInvariant()}_TYPES_H";
        var sb = new StringBuilder();

        sb.AppendLine("/* -----------------------------------------------------------------------------");
        sb.AppendLine($"   {buses[0].ProjectName} - shared type declarations");
        sb.AppendLine("   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.");
        sb.AppendLine();
        sb.AppendLine("   Types are project-wide, so a struct used by two buses is one struct. It is declared");
        sb.AppendLine("   here so that several bus headers can be included in the same translation unit.");
        sb.AppendLine("   ----------------------------------------------------------------------------- */");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine($"#include \"{CRuntimeHeader.FileName}\"");
        sb.AppendLine();
        OpenExternC(sb, options);

        // Named primitives declare no type — the host kind is already a built-in — but their wire size is
        // the thing a caller cannot derive, so it is emitted first and on its own.
        var seenPrimitives = new HashSet<string>(StringComparer.Ordinal);
        var primitives = buses.SelectMany(b => b.Primitives).Where(p => seenPrimitives.Add(p.Name)).ToList();
        if (primitives.Count > 0)
        {
            sb.AppendLine("/* Wire sizes of the named primitives. There is no type to declare - the host");
            sb.AppendLine("   kind is a built-in - but the width each one occupies is worth stating. */");
            foreach (var p in primitives)
                EmitTypeSize(sb, prefix, p.Name, p.WireBits, withNote: false);
            sb.AppendLine();
        }

        // Deduplicate by name across buses: the same project type reaches several of them and would
        // otherwise be declared once per bus. Two genuinely different types sharing a name is already a
        // validation warning (PD0005), so first-wins is safe here.
        var seenEnums = new HashSet<string>(StringComparer.Ordinal);
        foreach (var e in buses.SelectMany(b => b.Enums))
            if (seenEnums.Add(e.Name)) EmitEnum(sb, prefix, e);

        var seenStructs = new HashSet<string>(StringComparer.Ordinal);
        foreach (var ir in buses)
            foreach (var s in ir.Structs)
                if (seenStructs.Add(s.Name)) EmitStruct(sb, prefix, ir, s);

        CloseExternC(sb, options);
        sb.AppendLine($"#endif /* {guard} */");
        return sb.ToString();
    }

    /// <summary>
    /// Opens the <c>extern "C"</c> block, unless the caller turned it off.
    /// </summary>
    /// <remarks>
    /// On by default because the whole reason this target emits C rather than C++ is that one header
    /// should serve both. A pure-C project loses nothing by leaving it on, so turning it off is for the
    /// rare caller who has a reason.
    /// </remarks>
    private static void OpenExternC(StringBuilder sb, GeneratorOptions options)
    {
        if (!options.Flag(ExternCOption, fallback: true)) return;

        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("extern \"C\" {");
        sb.AppendLine("#endif");
        sb.AppendLine();
    }

    private static void CloseExternC(StringBuilder sb, GeneratorOptions options)
    {
        if (options.Flag(ExternCOption, fallback: true))
        {
            sb.AppendLine("#ifdef __cplusplus");
            sb.AppendLine("}   /* extern \"C\" */");
            sb.AppendLine("#endif");
        }
        sb.AppendLine();
    }

    // ---- protocol header ----------------------------------------------------------------------

    private static string EmitProtocolHeader(ProtocolIr ir, GeneratorOptions options)
    {
        var prefix = Prefix(options);
        var guard = $"PROTODESIGNER_{CNaming.TypeName("", ir.BusName).ToUpperInvariant()}_H";
        var sb = new StringBuilder();

        sb.AppendLine("/* -----------------------------------------------------------------------------");
        sb.AppendLine($"   {ir.ProjectName} - bus '{ir.BusName}' ({ir.Transport})");
        sb.AppendLine("   Generated by ProtoDesigner. Do not edit; regenerate from the .pdproj instead.");
        sb.AppendLine("   ----------------------------------------------------------------------------- */");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine($"#include \"{TypesFileName(options)}\"");
        sb.AppendLine();
        OpenExternC(sb, options);

        EmitMessageIdEnum(sb, prefix, ir);

        foreach (var m in ir.Messages) EmitMessage(sb, prefix, ir, m);

        CloseExternC(sb, options);
        sb.AppendLine($"#endif /* {guard} */");
        return sb.ToString();
    }

    private static void EmitEnum(StringBuilder sb, string prefix, IrEnum e)
    {
        var name = CNaming.TypeName(prefix, e.Name);

        sb.AppendLine($"/* {(e.IsFlags ? "Flag set" : "Enumeration")} '{e.Name}'. */");
        sb.AppendLine($"typedef enum {name} {{");
        foreach (var m in e.Members)
            sb.AppendLine($"    {CNaming.EnumMemberName(prefix, e.Name, m.Name)} = {m.Value.ToString(CultureInfo.InvariantCulture)},");
        sb.AppendLine($"}} {name};");
        EmitTypeSize(sb, prefix, e.Name, e.WireBits);
        sb.AppendLine();
    }

    /// <summary>
    /// Emits a type's wire size next to its declaration, as a macro.
    /// </summary>
    /// <remarks>
    /// The byte constant is emitted only for a whole number of bytes. A 4-bit enum has no byte size, and
    /// a rounded one would be wrong in exactly the place it would be trusted — sizing a buffer or
    /// stepping over a field.
    /// </remarks>
    private static void EmitTypeSize(StringBuilder sb, string prefix, string typeName, int wireBits, bool withNote = true)
    {
        if (wireBits <= 0) return;

        if (withNote)
        {
            sb.AppendLine($"/* Wire size of {typeName} itself. An individual field may narrow it - check the");
            sb.AppendLine("   field's own width in the message below before assuming this one applies to it. */");
        }
        sb.AppendLine($"#define {CNaming.MacroName(prefix, typeName, "ON_WIRE_BITS")} {wireBits}");
        if (wireBits % 8 == 0)
            sb.AppendLine($"#define {CNaming.MacroName(prefix, typeName, "ON_WIRE_BYTES")} {wireBits / 8}");
    }

    /// <summary>
    /// Emits a shared struct type. Declared once and referenced by name, so a Header used by ten messages
    /// appears once rather than being inlined into each of them.
    /// </summary>
    private static void EmitStruct(StringBuilder sb, string prefix, ProtocolIr ir, IrStruct s)
    {
        var name = CNaming.TypeName(prefix, s.Name);

        sb.AppendLine($"/* Struct '{s.Name}'. */");
        sb.AppendLine($"typedef struct {name} {{");
        foreach (var member in s.Members) EmitMember(sb, prefix, ir, member);
        sb.AppendLine($"}} {name};");
        EmitTypeSize(sb, prefix, s.Name, s.WireBits);
        sb.AppendLine();
    }

    /// <summary>
    /// Emits the bus's message-id enum plus a lookup from a wire id onto it.
    /// </summary>
    /// <remarks>
    /// Ids are scoped to a bus and start at 1, so <c>NotAssigned = 0</c> is a safe sentinel: no real
    /// message can collide with it. Read the id off the frame yourself, ask what it is, then call the
    /// matching <c>_ConvertToHost</c>.
    /// </remarks>
    private static void EmitMessageIdEnum(StringBuilder sb, string prefix, ProtocolIr ir)
    {
        var busType = CNaming.TypeName(prefix, ir.BusName + "MessageId");
        var identified = ir.Messages.Where(m => m.WireId is > 0).OrderBy(m => m.WireId!.Value).ToList();
        var enumScope = ir.BusName + "MessageId";

        sb.AppendLine($"/* Every message on bus '{ir.BusName}' that carries an id. Ids are unique within a");
        sb.AppendLine("   bus and start at 1, so 0 is free to mean \"no such message\". */");
        sb.AppendLine($"typedef enum {busType} {{");
        sb.AppendLine($"    {CNaming.EnumMemberName(prefix, enumScope, "NotAssigned")} = 0,");
        foreach (var m in identified)
            sb.AppendLine($"    {CNaming.EnumMemberName(prefix, enumScope, m.Name)} = {m.WireId!.Value},");
        sb.AppendLine($"}} {busType};");
        sb.AppendLine();

        var fn = CNaming.FunctionName(prefix, ir.BusName, "MessageIdFromWire");
        sb.AppendLine("/* Maps a wire id onto the message it identifies, or NotAssigned if this bus has none. */");
        sb.AppendLine($"PD_INLINE {busType} {fn}(uint32_t id) {{");
        if (identified.Count == 0)
        {
            sb.AppendLine("    (void)id;   /* no message on this bus carries an id */");
        }
        else
        {
            sb.AppendLine("    switch (id) {");
            foreach (var m in identified)
                sb.AppendLine($"        case {m.WireId!.Value}u: return {CNaming.EnumMemberName(prefix, enumScope, m.Name)};");
            sb.AppendLine("        default: break;");
            sb.AppendLine("    }");
        }
        sb.AppendLine($"    return {CNaming.EnumMemberName(prefix, enumScope, "NotAssigned")};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMessage(StringBuilder sb, string prefix, ProtocolIr ir, IrMessage m)
    {
        var name = CNaming.TypeName(prefix, m.Name);
        var maxBytesMacro = CNaming.MacroName(prefix, m.Name, "MAX_BYTES");

        sb.AppendLine($"/* Message '{m.Name}'"
            + (m.WireId is { } w ? $" (wire id {w})" : "")
            + (m.MinBits == m.MaxBits
                ? $" - fixed {m.MinBits} bits / {(m.MinBits + 7) / 8} bytes. */"
                : $" - {m.MinBits}..{m.MaxBits} bits / {(m.MinBits + 7) / 8}..{(m.MaxBits + 7) / 8} bytes. */"));

        // A C struct cannot carry constants, so they become macros ahead of it.
        if (m.WireId is { } wireId)
            sb.AppendLine($"#define {CNaming.MacroName(prefix, m.Name, "WIRE_ID")} {wireId}u");
        sb.AppendLine($"#define {maxBytesMacro} {(m.MaxBits + 7) / 8}");
        sb.AppendLine();

        sb.AppendLine($"typedef struct {name} {{");

        // Members, not Fields: the host shape the user declared, with structs kept whole.
        foreach (var member in m.Members) EmitMember(sb, prefix, ir, member);

        sb.AppendLine($"}} {name};");
        sb.AppendLine();

        EmitOnWireLength(sb, prefix, m, name);
        EmitEncode(sb, prefix, ir, m, name, maxBytesMacro);
        EmitDecode(sb, prefix, ir, m, name);
    }

    private static void EmitMember(StringBuilder sb, string prefix, ProtocolIr ir, IrMember member)
    {
        var name = CNaming.MemberName(member.Name);
        var type = member.Kind switch
        {
            IrMemberKind.EnumRef when member.EnumIndex is { } ei => CNaming.TypeName(prefix, ir.Enums[ei].Name),
            IrMemberKind.StructRef when member.StructIndex is { } si => CNaming.TypeName(prefix, ir.Structs[si].Name),
            _ => CNaming.StorageType(member.Primitive),
        };

        if (member.ArrayCapacity is { } capacity)
        {
            if (member.Note is not null) sb.AppendLine($"    /* '{member.Name}': {member.Note} */");
            sb.AppendLine($"    {type} {name}[{capacity}];");

            // Only a self-describing array carries its own count; see IrMember.NeedsCountMember.
            if (member.NeedsCountMember) sb.AppendLine($"    uint32_t {name}_count;");
            return;
        }

        var note = member.Note is null ? "" : $"   /* {member.Note} */";
        sb.AppendLine($"    {type} {name};{note}");
    }

    // ---- on-wire length -------------------------------------------------------------------------

    /// <summary>
    /// Emits the message's on-wire length in bytes.
    /// </summary>
    /// <remarks>
    /// It answers the question before encoding, which is what makes it worth generating: size a buffer,
    /// or locate a trailing field as <c>OnWireLength(msg) - &lt;TYPE&gt;_ON_WIRE_BYTES</c>. That stays
    /// right when fields are reordered, because both halves are regenerated. The walk mirrors
    /// <c>WireLength</c> in the Core and the encoder below, region by region, including the pad-to-byte
    /// at the end of each fixed region.
    /// </remarks>
    private static void EmitOnWireLength(StringBuilder sb, string prefix, IrMessage m, string structName)
    {
        var fn = CNaming.FunctionName(prefix, m.Name, "OnWireLength");
        var isFixed = m.Regions.All(r => r.Kind == IrRegionKind.Fixed);

        sb.AppendLine("/* The number of bytes this message occupies on the wire. */");

        if (isFixed)
        {
            sb.AppendLine($"PD_INLINE size_t {fn}(const {structName}* msg) {{");
            sb.AppendLine("    (void)msg;   /* fixed size: the contents do not matter */");
            sb.AppendLine($"    return {CNaming.MacroName(prefix, m.Name, "MAX_BYTES")};");
            sb.AppendLine("}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine($"PD_INLINE size_t {fn}(const {structName}* msg) {{");
        sb.AppendLine("    size_t bits = 0;");

        foreach (var region in m.Regions)
        {
            if (region.Kind == IrRegionKind.Fixed)
            {
                if (region.MaxBits > 0)
                {
                    sb.AppendLine($"    bits += {region.MaxBits};                 /* region {region.Index} (Fixed) */");
                    sb.AppendLine("    bits = ((bits + 7) / 8) * 8;   /* the encoder pads each fixed region to a byte */");
                }
                continue;
            }

            sb.AppendLine($"    {{   /* region {region.Index} (Variable), up to {region.MaxElements} x {region.ElementBits} bits */");
            sb.AppendLine($"        size_t n = (size_t)({CountExpression(m, region)});");
            sb.AppendLine($"        if (n > {region.MaxElements}) n = {region.MaxElements};   /* the encoder truncates at capacity */");
            if (region.PrefixBits > 0)
                sb.AppendLine($"        bits += {region.PrefixBits};                /* inline length prefix */");
            sb.AppendLine($"        bits += n * {region.ElementBits};");
            sb.AppendLine("    }");
        }

        sb.AppendLine("    return (bits + 7) / 8;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>How many elements a variable region carries, as a C expression over the host struct.</summary>
    private static string CountExpression(IrMessage m, IrRegion region)
    {
        if (region.CountFieldIndex is { } ci)
            return $"msg->{CNaming.MemberPath(m.Fields[ci].Path)}";

        var arrayField = m.Fields.FirstOrDefault(f => f.RegionIndex == region.Index && f.Array is not null);
        return arrayField is null ? "0" : $"msg->{CNaming.MemberPath(arrayField.Path)}_count";
    }

    // ---- encode -------------------------------------------------------------------------------

    private static void EmitEncode(StringBuilder sb, string prefix, ProtocolIr ir, IrMessage m,
        string structName, string maxBytesMacro)
    {
        var fn = CNaming.FunctionName(prefix, m.Name, "ConvertToWire");

        sb.AppendLine("/* Converts the host struct `msg` into its on-wire form in `wire` (capacity `cap` bytes).");
        sb.AppendLine($"   Returns the number of bytes written, or 0 if the buffer was too small.");
        sb.AppendLine($"   A correctly sized buffer is uint8_t wire[{maxBytesMacro}]. */");
        sb.AppendLine($"PD_INLINE size_t {fn}(const {structName}* msg, uint8_t* wire, size_t cap) {{");
        sb.AppendLine("    pd_bit_writer_t w;");
        sb.AppendLine("    pd_bw_init(&w, wire, cap);");

        foreach (var region in m.Regions)
        {
            var fields = m.Fields.Where(f => f.RegionIndex == region.Index).ToList();
            if (fields.Count == 0 && region.Kind == IrRegionKind.Fixed) continue;

            sb.AppendLine();
            sb.AppendLine($"    /* --- region {region.Index} ({region.Kind}) --- */");
            sb.AppendLine($"    {{ const size_t r{region.Index} = pd_bw_bit_length(&w);");

            foreach (var f in fields)
            {
                sb.AppendLine($"    /* {f.Path} */");
                sb.AppendLine($"    if (pd_bw_bit_length(&w) < r{region.Index} + {f.BitOffset}) pd_bw_skip(&w, r{region.Index} + {f.BitOffset} - pd_bw_bit_length(&w));");
                EmitEncodeField(sb, prefix, ir, m, f);
            }

            if (region.Kind == IrRegionKind.Fixed)
                sb.AppendLine("    pd_bw_pad_to(&w, 8);");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine("    if (pd_bw_overflowed(&w)) return 0;");
        sb.AppendLine("    return pd_bw_byte_length(&w);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitEncodeField(StringBuilder sb, string prefix, ProtocolIr ir, IrMessage m, IrField f)
    {
        var member = CNaming.MemberPath(f.Path);
        var endian = EndianExpr(f.Endianness);

        if (f.Kind == IrFieldKind.Array && f.Array is { } arr)
        {
            var countExpr = arr.Kind switch
            {
                IrArrayKind.Fixed => arr.ElementCount!.Value.ToString(CultureInfo.InvariantCulture),
                // The count field is the single source of truth — read it, don't shadow it.
                IrArrayKind.CountFromField when arr.CountFieldIndex is { } ci =>
                    $"msg->{CNaming.MemberPath(m.Fields[ci].Path)}",
                _ => $"msg->{member}_count",
            };

            if (arr.Kind == IrArrayKind.LengthPrefixed)
                sb.AppendLine($"    pd_bw_write_unsigned(&w, (uint64_t)({countExpr}), {arr.PrefixBits}, PD_ENDIAN_LITTLE);");

            sb.AppendLine($"    for (size_t i = 0; i < (size_t)({countExpr}) && i < {arr.MaxElements}; ++i) {{");
            var elemAccess = arr.ElementEnumIndex is not null
                ? $"(int64_t)(msg->{member}[i])"
                : $"msg->{member}[i]";
            var elemWire = IsRawFloat(arr.ElementPrimitive, f.Transform)
                ? (arr.ElementPrimitive == PrimitiveKind.F32
                    ? $"pd_float_bits(msg->{member}[i])"
                    : $"pd_double_bits(msg->{member}[i])")
                : ToWireCode(elemAccess, f.Transform, arr.ElementPrimitive);
            if (IsRawFloat(arr.ElementPrimitive, f.Transform))
                sb.AppendLine($"        pd_bw_write_unsigned(&w, (uint64_t)({elemWire}), {arr.ElementBits}, {endian});");
            else if (f.WireIsSigned)
                sb.AppendLine($"        pd_bw_write_signed(&w, (int64_t)({elemWire}), {arr.ElementBits}, {endian});");
            else
                sb.AppendLine($"        pd_bw_write_unsigned(&w, (uint64_t)({elemWire}), {arr.ElementBits}, {endian});");
            sb.AppendLine("    }");

            if (arr.Kind == IrArrayKind.Terminated && arr.Sentinel.Count > 0)
            {
                var bytes = string.Join(", ", arr.Sentinel.Select(b => $"0x{b:X2}"));
                sb.AppendLine($"    {{ static const uint8_t kSentinel[] = {{ {bytes} }}; pd_bw_write_bytes(&w, kSentinel, {arr.Sentinel.Count}); }}");
            }
            return;
        }

        // A float host with no transform means the IEEE bit pattern goes on the wire verbatim. Casting
        // the value to an integer instead would keep 3 of 3.14159 and throw the rest away.
        if (IsRawFloat(f.Primitive, f.Transform))
        {
            var bitsCall = f.Primitive == PrimitiveKind.F32
                ? $"pd_float_bits(msg->{member})"
                : $"pd_double_bits(msg->{member})";
            sb.AppendLine($"    pd_bw_write_unsigned(&w, (uint64_t)({bitsCall}), {f.BitWidth}, {endian});");
            return;
        }

        var access = f.Kind == IrFieldKind.EnumRef
            ? $"(int64_t)(msg->{member})"
            : $"msg->{member}";
        var wire = ToWireCode(access, f.Transform, f.Primitive);

        if (f.WireIsSigned)
            sb.AppendLine($"    pd_bw_write_signed(&w, (int64_t)({wire}), {f.BitWidth}, {endian});");
        else
            sb.AppendLine($"    pd_bw_write_unsigned(&w, (uint64_t)({wire}), {f.BitWidth}, {endian});");
    }

    // ---- decode -------------------------------------------------------------------------------

    private static void EmitDecode(StringBuilder sb, string prefix, ProtocolIr ir, IrMessage m, string structName)
    {
        var fn = CNaming.FunctionName(prefix, m.Name, "ConvertToHost");

        sb.AppendLine("/* Converts the on-wire bytes `wire` (`len` of them) back into the host struct `msg`.");
        sb.AppendLine("   Returns pd_decode_ok() on success, or pd_decode_fail(bit) if the frame ran out early. */");
        sb.AppendLine($"PD_INLINE pd_decode_result_t {fn}(const uint8_t* wire, size_t len, {structName}* msg) {{");
        sb.AppendLine("    pd_bit_reader_t r;");
        sb.AppendLine("    pd_br_init(&r, wire, len);");

        foreach (var region in m.Regions)
        {
            var fields = m.Fields.Where(f => f.RegionIndex == region.Index).ToList();
            if (fields.Count == 0 && region.Kind == IrRegionKind.Fixed) continue;

            sb.AppendLine();
            sb.AppendLine($"    /* --- region {region.Index} ({region.Kind}) --- */");
            sb.AppendLine($"    {{ const size_t r{region.Index} = pd_br_bit_offset(&r);");

            foreach (var f in fields)
            {
                sb.AppendLine($"    /* {f.Path} */");
                sb.AppendLine($"    if (pd_br_bit_offset(&r) < r{region.Index} + {f.BitOffset}) pd_br_skip(&r, r{region.Index} + {f.BitOffset} - pd_br_bit_offset(&r));");
                EmitDecodeField(sb, prefix, ir, m, f);
            }

            if (region.Kind == IrRegionKind.Fixed)
                sb.AppendLine("    pd_br_align_to(&r, 8);");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine("    if (pd_br_underflowed(&r)) return pd_decode_fail(pd_br_bit_offset(&r));");
        sb.AppendLine("    return pd_decode_ok();");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitDecodeField(StringBuilder sb, string prefix, ProtocolIr ir, IrMessage m, IrField f)
    {
        var member = CNaming.MemberPath(f.Path);
        var endian = EndianExpr(f.Endianness);

        if (f.Kind == IrFieldKind.Array && f.Array is { } arr)
        {
            string countExpr;
            switch (arr.Kind)
            {
                case IrArrayKind.Fixed:
                    countExpr = arr.ElementCount!.Value.ToString(CultureInfo.InvariantCulture);
                    break;
                case IrArrayKind.CountFromField when arr.CountFieldIndex is { } ci:
                    // The count field was decoded earlier in this same message; read it directly.
                    countExpr = $"msg->{CNaming.MemberPath(m.Fields[ci].Path)}";
                    break;
                case IrArrayKind.LengthPrefixed:
                    sb.AppendLine($"    msg->{member}_count = (uint32_t)pd_br_read_unsigned(&r, {arr.PrefixBits}, PD_ENDIAN_LITTLE);");
                    countExpr = $"msg->{member}_count";
                    break;
                default:
                    sb.AppendLine($"    /* {arr.Kind} arrays consume the remainder; the caller supplies the count. */");
                    countExpr = $"msg->{member}_count";
                    break;
            }

            sb.AppendLine($"    for (size_t i = 0; i < (size_t)({countExpr}) && i < {arr.MaxElements}; ++i) {{");
            var elemType = arr.ElementEnumIndex is { } ei
                ? CNaming.TypeName(prefix, ir.Enums[ei].Name)
                : CNaming.StorageType(arr.ElementPrimitive);

            if (IsRawFloat(arr.ElementPrimitive, f.Transform))
            {
                var fromBits = arr.ElementPrimitive == PrimitiveKind.F32
                    ? $"pd_bits_to_float((uint32_t)pd_br_read_unsigned(&r, {arr.ElementBits}, {endian}))"
                    : $"pd_bits_to_double((uint64_t)pd_br_read_unsigned(&r, {arr.ElementBits}, {endian}))";
                sb.AppendLine($"        msg->{member}[i] = {fromBits};");
            }
            else
            {
                var readCall = f.WireIsSigned
                    ? $"pd_br_read_signed(&r, {arr.ElementBits}, {endian})"
                    : $"pd_br_read_unsigned(&r, {arr.ElementBits}, {endian})";
                var fromWire = FromWireCode(readCall, f.Transform, arr.ElementPrimitive);
                sb.AppendLine($"        msg->{member}[i] = ({elemType})({fromWire});");
            }
            sb.AppendLine("    }");

            if (arr.Kind == IrArrayKind.Terminated && arr.Sentinel.Count > 0)
                sb.AppendLine($"    pd_br_skip(&r, {arr.Sentinel.Count * 8});   /* sentinel */");
            return;
        }

        if (IsRawFloat(f.Primitive, f.Transform))
        {
            var fromBits = f.Primitive == PrimitiveKind.F32
                ? $"pd_bits_to_float((uint32_t)pd_br_read_unsigned(&r, {f.BitWidth}, {endian}))"
                : $"pd_bits_to_double((uint64_t)pd_br_read_unsigned(&r, {f.BitWidth}, {endian}))";
            sb.AppendLine($"    msg->{member} = {fromBits};");
            return;
        }

        var call = f.WireIsSigned
            ? $"pd_br_read_signed(&r, {f.BitWidth}, {endian})"
            : $"pd_br_read_unsigned(&r, {f.BitWidth}, {endian})";
        var value = FromWireCode(call, f.Transform, f.Primitive);
        var type = f.Kind == IrFieldKind.EnumRef && f.EnumIndex is { } idx
            ? CNaming.TypeName(prefix, ir.Enums[idx].Name)
            : CNaming.StorageType(f.Primitive);

        sb.AppendLine($"    msg->{member} = ({type})({value});");
    }

    // ---- transform helpers ---------------------------------------------------------------------

    private static string EndianExpr(Endianness e) =>
        e == Endianness.Big ? "PD_ENDIAN_BIG" : "PD_ENDIAN_LITTLE";

    /// <summary>
    /// <c>wire = (value - offset) / scale</c>, wrapped in a round-to-nearest when the maths is
    /// floating-point.
    /// </summary>
    /// <remarks>
    /// The rounding is not cosmetic. Assigning a <c>double</c> to an integer truncates toward zero, so a
    /// -40..70 field scaled by 110/255 turns 70.0 into 254.99999999999997 and stores 254 — the top code
    /// the width was chosen for is never reached, and every other reading is biased low by up to a full
    /// code. Integer pipelines are left alone: forcing them through a <c>double</c> would lose precision
    /// above 2^53 for no gain.
    /// </remarks>
    private static string ToWireCode(string valueExpr, ScalarTransform t, PrimitiveKind host)
    {
        if (t.IsIdentity) return valueExpr;

        var expr = valueExpr;
        if (t.Offset != 0m) expr = $"(({expr}) {Signed(-t.Offset)})";
        if (t.Scale != 1m) expr = $"(({expr}) / {Dec(t.Scale)})";

        return IsFloatingMath(t, host) ? $"pd_quantize({expr})" : expr;
    }

    /// <summary><c>value = (wire * scale) + offset</c>.</summary>
    private static string FromWireCode(string wireExpr, ScalarTransform t, PrimitiveKind host)
    {
        if (t.IsIdentity) return wireExpr;

        var expr = wireExpr;
        if (t.Scale != 1m) expr = $"(({expr}) * {Dec(t.Scale)})";
        if (t.Offset != 0m) expr = $"(({expr}) {Signed(t.Offset)})";

        // Coming back the other way, a float host keeps the fractional part — that IS the decoded value —
        // so only an integer host needs the result rounded rather than truncated.
        return IsFloatingMath(t, host) && !IsFloat(host) ? $"pd_quantize({expr})" : expr;
    }

    /// <summary>
    /// Whether the emitted expression is evaluated in floating point: either the host is a float, or the
    /// scale is fractional and drags the whole expression into <c>double</c>.
    /// </summary>
    private static bool IsFloatingMath(ScalarTransform t, PrimitiveKind host) =>
        IsFloat(host) || decimal.Truncate(t.Scale) != t.Scale;

    /// <summary>
    /// A float host with no transform: the IEEE bit pattern goes on the wire untouched. The propagator
    /// guarantees the pairing — a float wire form produces no transform, and any integer wire form on a
    /// float host always produces one.
    /// </summary>
    private static bool IsRawFloat(PrimitiveKind host, ScalarTransform t) => IsFloat(host) && t.IsIdentity;

    private static bool IsFloat(PrimitiveKind kind) => kind is PrimitiveKind.F32 or PrimitiveKind.F64;

    /// <summary>Renders a term as <c>+ n</c> or <c>- n</c>, so an offset of -40 reads `+ 40`, not `- -40`.</summary>
    private static string Signed(decimal value) =>
        value < 0m ? $"- {Dec(-value)}" : $"+ {Dec(value)}";

    /// <summary>
    /// Emits a transform constant as a C literal.
    /// </summary>
    /// <remarks>
    /// Integral values stay integral so an otherwise-integer pipeline is not forced into floating-point
    /// maths. Everything else becomes a <c>double</c> literal — never a <c>float</c> one. A derived scale
    /// is <c>(max - min) / (2^bits - 1)</c>, which carries far more significant digits than float's ~7:
    /// rounding 110/255 down to float puts the top of a -40..70 range at 254.99999 of 255 codes, and the
    /// cast to an integer then truncates it to 254. The whole top of the range would be off by one.
    /// </remarks>
    private static string Dec(decimal value)
    {
        if (decimal.Truncate(value) == value && Math.Abs(value) < 1e18m)
            return decimal.ToInt64(value).ToString(CultureInfo.InvariantCulture);

        // "R" gives the shortest form that round-trips back to the same double, so the emitted constant
        // names exactly the double the C# side would compute from the same decimal.
        var text = ((double)value).ToString("R", CultureInfo.InvariantCulture);
        return text.Contains('.') || text.Contains('E') || text.Contains('e') ? text : text + ".0";
    }

    // ---- readme --------------------------------------------------------------------------------

    private static string EmitReadme(IReadOnlyList<ProtocolIr> buses, GeneratorOptions options)
    {
        var prefix = Prefix(options);
        var sb = new StringBuilder();

        sb.AppendLine($"# {buses[0].ProjectName} — generated C codec");
        sb.AppendLine();
        sb.AppendLine("Generated by ProtoDesigner. Do not edit these files; change the `.pdproj` and regenerate.");
        sb.AppendLine();
        sb.AppendLine($"- Buses: {string.Join(", ", buses.Select(b => $"`{b.BusName}`"))}");
        sb.AppendLine($"- Symbol prefix: `{prefix}_`");
        sb.AppendLine("- Standard: C99, header-only, no allocation. Compiles as C or as C++.");
        sb.AppendLine();
        sb.AppendLine("C has no namespaces, so every symbol carries the prefix above. It compiles under a C++");
        sb.AppendLine("compiler too — the headers wrap themselves in `extern \"C\"` — so one definition serves a C");
        sb.AppendLine("module and a C++ module without either having to care what the other is written in.");
        sb.AppendLine();
        sb.AppendLine("## Files");
        sb.AppendLine();
        sb.AppendLine("| File | Contents |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| `{CRuntimeHeader.FileName}` | The bit cursor everything else is built on |");
        sb.AppendLine($"| `{TypesFileName(options)}` | Shared enums and structs — project-wide, so declared once |");
        foreach (var ir in buses)
            sb.AppendLine($"| `{FileStem(ir.BusName)}.h` | Messages on bus `{ir.BusName}` and their conversions |");
        sb.AppendLine();

        sb.AppendLine("## Messages");
        sb.AppendLine();
        sb.AppendLine("| Bus | Message | Message id | Size | Fields |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var ir in buses)
            foreach (var m in ir.Messages)
                sb.AppendLine($"| `{ir.BusName}` | `{m.Name}` | {(m.WireId?.ToString(CultureInfo.InvariantCulture) ?? "—")} "
                    + $"| {(m.MinBits == m.MaxBits ? $"{(m.MaxBits + 7) / 8} B" : $"{(m.MinBits + 7) / 8}..{(m.MaxBits + 7) / 8} B")} "
                    + $"| {m.Fields.Count} |");
        sb.AppendLine();

        var first = buses[0].Messages.FirstOrDefault();
        if (first is not null)
        {
            var type = CNaming.TypeName(prefix, first.Name);
            var maxBytes = CNaming.MacroName(prefix, first.Name, "MAX_BYTES");

            sb.AppendLine("## Usage");
            sb.AppendLine();
            sb.AppendLine("```c");
            sb.AppendLine($"#include \"{FileStem(buses[0].BusName)}.h\"");
            sb.AppendLine();
            sb.AppendLine("/* The struct is the HOST representation: plain fields, no packing, no scaling. */");
            sb.AppendLine($"{type} msg;");
            sb.AppendLine("/* ... populate msg ... */");
            sb.AppendLine();
            sb.AppendLine("/* Host -> wire. */");
            sb.AppendLine($"uint8_t wire[{maxBytes}];");
            sb.AppendLine($"size_t written = {CNaming.FunctionName(prefix, first.Name, "ConvertToWire")}(&msg, wire, sizeof(wire));");
            sb.AppendLine("if (written == 0) { /* buffer too small */ }");
            sb.AppendLine();
            sb.AppendLine("/* Wire -> host. */");
            sb.AppendLine($"{type} parsed;");
            sb.AppendLine($"pd_decode_result_t status = {CNaming.FunctionName(prefix, first.Name, "ConvertToHost")}(wire, written, &parsed);");
            sb.AppendLine("if (!status.ok) { /* truncated frame */ }");
            sb.AppendLine("```");
            sb.AppendLine();
        }

        sb.AppendLine("## Finding a field without storing an offset");
        sb.AppendLine();
        sb.AppendLine("Checksums and CRCs are not modelled — a checksum is an ordinary field you fill in. What is");
        sb.AppendLine("generated is the size information needed to place one, regenerated on every edit:");
        sb.AppendLine();
        sb.AppendLine("```c");
        sb.AppendLine("/* <TYPE>_ON_WIRE_BYTES per type, <Msg>_OnWireLength(msg) per message. */");
        if (first is not null)
            sb.AppendLine($"size_t len = {CNaming.FunctionName(prefix, first.Name, "OnWireLength")}(&msg);");
        sb.AppendLine("/* a trailing field then sits at len - <TYPE>_ON_WIRE_BYTES */");
        sb.AppendLine("```");

        return sb.ToString();
    }
}
